stubs/SampleValetDriver.php
Just add a closing bracket to the if statement in an example in the `stubs/SampleValetDriver.php`
=> Fix missing bracket

mimes.php
The title is pretty self-explanatory...
=> Add woff2 missing mime type

drivers/SymfonyValetDriver.php, drivers/ValetDriver.php, server.php
This driver should work for both Symfony V2 and V3.
It could be split in two separate drivers if necessary
=> Symfony2/3 Valet driver

drivers/SculpinValetDriver.php, drivers/require.php
Add driver for [sculpin.io](https://sculpin.io/documentation/basic-project/)
=> Add Sculpin Valet driver

drivers/BasicValetDriver.php, drivers/CraftValetDriver.php, drivers/LaravelValetDriver.php, drivers/SculpinValetDriver.php, drivers/StatamicValetDriver.php, drivers/WordPressValetDriver.php
=> Fix docblocks

drivers/KirbyValetDriver.php, drivers/ValetDriver.php, drivers/require.php
=> Add Kirby CMS driver

server.php, src/DnsMasq.php
If someone uses different home directory (like me) it does not work.
=> Remove '/Users/' prefix

drivers/KatanaValetDriver.php, drivers/ValetDriver.php, drivers/require.php
Following up on https://github.com/laravel/valet/pull/10, after merging updates.
=> Add Katana Driver

src/Caddy.php, stubs/Caddyfile, tests/CaddyTest.php
=> Fix Caddyfile path

cli/includes/helpers.php, cli/valet.php
Just a helper to output a warning.
=> Add warning() helper

cli/drivers/JoomlaValetDriver.php, cli/drivers/ValetDriver.php, cli/drivers/require.php
Created a basic driver for Joomla.
=> Created a driver for Joomla

cli/Valet/Brew.php, cli/Valet/Caddy.php, cli/Valet/Configuration.php, cli/Valet/Filesystem.php, cli/Valet/PhpFpm.php, cli/Valet/Site.php, cli/Valet/Valet.php, cli/drivers/StatamicV1ValetDriver.php, cli/drivers/ValetDriver.php, cli/stubs/SampleValetDriver.php
Some simple changes for consistency and IDE warning suppression.
Let me know if you would prefer these commits squashed.
=> Consistency changes

.editorconfig, .gitattributes
=> Add some dotfiles

tests/CaddyTest.php, tests/PhpFpmTest.php
=> Remove useless imports

tests/BrewTest.php, tests/CaddyTest.php, tests/DnsMasqTest.php, tests/FilesystemTest.php, tests/SiteTest.php
=> Use proper tests assertions

cli/valet.php
Similar to #89 and #91
Missed again. So. Close. 😄
=> Update version to match release

cli/valet.php
Allow path parameter for `valet park` and `valet forget`
Fixes #107
=> Allow path parameter for valet park and forget

readme.md
Updated to Laravel 5.3 docs. This is similar to #127 but this PR also updates to HTTPS.
=> Update Laravel docs link

cli/valet.php
Thanks to @adamwathan for the help
=> Added Share Command to the List of Commands

composer.json
Switched from gmail to laravel.com
=> Update Taylors email

readme.md
Right now on main README it shows failed because of nginx branch.
=> Show proper Travis badge

cli/Valet/Brew.php, cli/Valet/PhpFpm.php, cli/includes/compatibility.php, composer.json, tests/BrewTest.php
Update minimum PHP requirement to 5.6 because it's not actually compatible with 5.5 anymore
Fixes #279
=> Update minimum PHP requirement to 5.6

cli/Valet/Site.php, cli/stubs/openssl.conf, cli/stubs/secure.valet.conf, server.php
This PR makes it so that any subdomain of a site resolves to that site, and when you `valet secure` it creates a wildcard ssl certificate so that any subdomain is secured.
=> [FEATURE] Add wildcard subdomains and accompanying ssl certificates.

cli/Valet/Brew.php, cli/Valet/Nginx.php
Fix for issue #250 - brew package nginx-full not properly recognized as a valid nginx installation
Now using the correct nginx service name for restart/stop :)
=> Fix for issue #250 - brew package nginx-full not properly recognized as a valid nginx installation

cli/stubs/secure.valet.conf
=> Fix for query string in secure config

cli/Valet/PhpFpm.php
Ref: https://github.com/laravel/valet/pull/261
=> Dry's up PHP installation

cli/Valet/Configuration.php, cli/Valet/Site.php, cli/includes/helpers.php, cli/valet.php
This is an expansion on https://github.com/laravel/valet/pull/234 like discussed in it.
It now shows all links in a table, their link name, if that link is secured, it's url to easily open, and the path of the link.
Preview of output:
=> [FEATURE] Pretty print sites

cli/drivers/Magento2ValetDriver.php, cli/drivers/ValetDriver.php, cli/drivers/require.php
Here is my version of the Magento2 driver as mentioned at the bottom of #47.  I've been using this as a local driver for several months now and it works great.
I've copied @sschlein instructions for testing from #47 below:
> To test this driver, run the following commands. Please make sure to have an empty database "magento" which can be accessed with the root user without a password on localhost.
> 
> composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento
> 
> cd magento
> 
> chmod a+x bin/magento
> 
> bin/magento setup:install --base-url=http://magento.dev/ \
> --db-host=localhost --db-name=magento --db-user=root --db-password= \
> --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com \
> --admin-user=admin …
=> Add Magento2 driver

cli/drivers/SymfonyValetDriver.php
=> Add new Symfony directory structure in driver

cli/drivers/CakeValetDriver.php
=> Added missing $_SERVER variables for CakePHP 3

valet
Always needs sudo since commit: fd595b5c7196cc83a00ab18c5598c6b7b333d38c
=> Remove outdated comment

cli/drivers/BasicValetDriver.php
https://github.com/laravel/valet/issues/379
=> Added missing $_SERVER variables for Basic Driver

cli/Valet/Configuration.php, cli/Valet/DnsMasq.php, tests/DnsMasqTest.php, tests/NginxTest.php
=> Dev => Localhost

composer.json
=> Add compatibility with symfony/process v4

cli/Valet/Site.php, tests/SiteTest.php
#495, plus a test.
Closes #495 
Fixes #445
=> Fix valet links non dev

cli/drivers/SymfonyValetDriver.php
reference: https://symfony.com/doc/current/setup/flex.html#upgrading-existing-applications-to-flex
=> Add support to Symfony Flex directory structure

cli/Valet/Brew.php, cli/Valet/PhpFpm.php
=> Revert "fix for new php versions/paths from php installed via brew"

cli/Valet/Brew.php, cli/Valet/CommandLine.php, tests/BrewTest.php, valet
=> Surround username with quotes (in case it has spaces)

cli/drivers/BasicValetDriver.php
This allows static file serving of 'index.php' and 'index.html' files from subfolders when you have a root 'public' folder.
=> Static file serving for subfolders

cli/Valet/CommandLine.php
Reverts #761, Fixes #763, then we need to figure out next steps.
=> Revert new fromShellCommandLine call

composer.json, tests/NginxTest.php
Fix tests for compatibility with PHP 7.4
=> Compatibility PHP 7.4

cli/drivers/StatamicValetDriver.php
Would be nice if the Chinese locale could be included in the list of possible locales.
=> Update StatamicValetDriver.php with locale 'zh'

server.php
Fixes https://github.com/laravel/valet/issues/829
=> Fix incorrectly decoding plus symbol to space in paths

tests/NginxTest.php
=> Fix misnamed test

cli/stubs/nginx.conf
Just re-ordering directives to keep gzip stuff together.
No impact to existing installs.
Updates #517
=> Update nginx.conf - keep gzip directives together

composer.json
=> chore: allow support for tightenco/collect:^7.0

cli/Valet/Configuration.php
=> Protect against un-parking Valet's core Sites folder

server.php
Fixes #622
/cc @jackfruhecolab @scottgrayson
=> Allow serving mixed case folders on case sensitive file systems

server.php
Prefer path matching the domain name over a path matching only the domain name.
=> prefer site name over domain name when detecting the site path

.github/issue_template.md
Offers some suggestions for self-repair before posting an issue.
=> Add some self-repair suggestions to the Issues template

.github/workflows/tests.yml
=> Add PHP 8.1 to Valet tests

cli/Valet/Site.php
Currently Laravel Valet creates a root certificate authority with the same validity period as normal certificates.
It is correct to limit normal certificates to a maximum of 396 days in order to adhere to certificate baseline-requirements as defined in https://github.com/cabforum/servercert/blob/main/docs/BR.md (2020-09-01).
But the validity of root CAs is not limited, thus it makes sense to create the root CA with a longer validity period. The Lets Encrypt Root CA `ISRG Root X1` has a validity period of 20 years, so that should also be the default period of the Laravel Valet Root CA.
This resolves #1103 without having to implement auto-rotation of expired root CAs. (Because the amount of people that use the same machine and OS for over 20 years is probably zero.)
There is only one …
=> Avoid expiring of root certificate authority

cli/Valet/Valet.php
=> Fixing `Attempt to read property "tag_name" on string` warning

cli/Valet/PhpFpm.php, cli/Valet/Site.php, cli/valet.php, tests/PhpFpmTest.php, tests/SiteTest.php
- Add `--site` to `isolate`
- Add `--site` to `unisolate`
- Refactor some tests
- Update `Site@getSiteUrl()` to throw an exception instead of returning `false`
- Fix a few minor typos/grammatical issues
Fixes #1206.
=> Add --site to isolate and unisolate commands

.github/ISSUE_TEMPLATE/1_Bug_report.md
As an alternative to https://github.com/laravel/docs/pull/7854
=> Temporarily note restart in bug report

cli/Valet/Ngrok.php, tests/NgrokTest.php, valet
=> Update Ngrok (valet share) to lowercase domains before matching

.github/workflows/tests.yml, cli/Valet/Brew.php, cli/Valet/PhpFpm.php, phpunit.xml.dist, tests/BrewTest.php
=> PHP 8.2 support

cli/valet.php
=> Add description to `secured` command

cli/Valet/Site.php
Fixes #1304 
It seems as though the condition was checking for the wrong stub line.
=> fix: retain secure proxies

cli/Valet/Configuration.php, cli/Valet/DnsMasq.php, cli/Valet/Filesystem.php, cli/Valet/Nginx.php, cli/Valet/PhpFpm.php, cli/Valet/Site.php, tests/SiteTest.php
Simplifying PR https://github.com/laravel/valet/pull/941 with this new one.
This will allow all stub files to be pulled from local VALET_HOME/stubs folder in case users want to create custom changes
=> use getStub to allow custom stub files

cli/includes/legacy/WordPressValetDriver.php, server.php
- Loads legacy drivers when loading the server.
- Fixes WordPressValetDriver reference.
=> Fix legacy driver alias implementation

cli/Valet/Valet.php, cli/app.php, tests/CliTest.php
=> (WIP) Add more CLI tests

.gitattributes, cli/Valet/Brew.php, cli/Valet/Composer.php, cli/Valet/Diagnose.php, cli/Valet/Expose.php, cli/Valet/Ngrok.php, cli/app.php, cli/includes/facades.php, cli/scripts/fetch-share-url.sh, composer.json, tests/BrewTest.php, tests/CliTest.php, tests/ComposerTest.php, tests/NgrokTest.php, valet
Closes #1340.
All that's missing is the code that will make it work to run `valet share` after setting `expose` as your share-tool. @mpociot will PR that later.
=> Add Expose support

cli/Valet/Status.php, tests/CliTest.php
=> Check whether services are running as the correct user in `valet status`

cli/Valet/Site.php, cli/app.php
=> Remove Valet Certificate Authority on uninstall

cli/Valet/Site.php, cli/app.php, tests/SiteTest.php
=> Update phpRc reader to check cwd before checking config, if cwd specified

cli/Valet/Site.php, cli/app.php, tests/CliTest.php, tests/SiteTest.php
=> Unsecure when unlinking

cli/Valet/Drivers/ValetDriver.php
This seems to resolve https://github.com/laravel/valet/issues/1383 for me.
=> Fixes Valet\Drivers\LocalValetDriver not found error

cli/Valet/Configuration.php, cli/app.php, tests/ConfigurationTest.php
=> Ensure base configuration is correct even if file already exists

valet
=> Add quotes around $PHP

cli/Valet/Brew.php
Fixes https://github.com/laravel/valet/issues/1506
=> Change latest php version to 8.4
