laravel/valet

- drivers/StaticValetDriver.php
- drivers/ValetDriver.php
- server.php
It would be really nice if we could use _valet_ even for some static sites. This pull request adds an option for that. Assuming that you have an `index.html` file in your project, you're ready to use it with _valet_ awesomeness.
> Add StaticValetDriver for static pages

- mimes.php
I hope that it's ok to add this here. I'm using Mustache templates in a Laravel project and I had the following error message in all my templates: "Notice: Undefined index: mustache in /Users/jan/.composer/vendor/laravel/valet/drivers/ValetDriver.php on line 97". Adding the mime type to mimes.php fixes this problem.
> Add mime types for Handlebars / Mustache templates

- drivers/ValetDriver.php
Docblock return type is not correct on ValetDriver::serves method. It should return boolean value whether driver serves request or not.
> ValetDriver::serves() method should return bool

- valet
This fixes paths with spaces when using `valet link` and `valet share`.
> Quote all variables in shell script

- drivers/GenericPublicValetDriver.php
- drivers/ValetDriver.php
- server.php
Adds Generic Support to a `public/` folder containing an `index.php` file.  Adds support for SlimPHP, Non-Framework PHP apps.
> Add Generic Driver to point to a public/ folder

- drivers/StatamicValetDriver.php
Statamic has a feature that saves fully rendered versions of pages to `.html` files located in `static`. Normally nginx or htaccess should be set up to load these. Now Valet can serve them out of the box.
To test in Statamic, open `site/settings/caching.yaml` and add:
```
static_caching_enabled: true
static_caching_type: file
```
Visit a page, and it'll get written to `static/url/of/page/index.html`. Visit the page again and now the response time should drop.
> Support Statamic static caching

- drivers/WordPressValetDriver.php
This fixes an error which is produced in wp-admin.  Although wp-admin seems to work fine already, it is silently triggering this error as WordPress does not show/log errors by default.  You can see this by adding `define('WP_DEBUG', true);` to `wp-config.php`
Basically, WP uses the `PHP_SELF` sever global to determine which admin page it is on, which is currently `server.php` everywhere.
`/wp-includes/vars.php`
This PR ensures that the global is defined in a way which should work with what WP expects.
> WordPress Driver: Fix undefined offset error in wp-admin

- valet.php
Use escapeshellarg to make file paths safe to use in shell command
> Escape file paths for 'logs' command

- drivers/ContaoValetDriver.php
- drivers/ValetDriver.php
- drivers/require.php
This driver targets the Contao CMS (quite common in Germany and expanding with it's 4.0 symfony based release https://contao.org/en/).
Contao install documentation: https://docs.contao.org/books/manual/4.0/en/01-installation/installing-contao.html
I've added a double check for the `serves` method to be sure Contao is used in the project && the project is served via the web directory. The `frontControllerPath` checks if the user want to run the installer instead the main file.
> Add Contao CMS driver

- .travis.yml
- cli/Valet/Brew.php
- cli/Valet/PhpFpm.php
- composer.json
- tests/BrewTest.php
Nothing in the code base seemed particularly hostile to PHP 5.5, so I decided to add support for it.
> Allows Valet to run under PHP 5.5

- cli/drivers/WordPressValetDriver.php
WordPress supports being placed in [it's own directory](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory), but in both setups the `wp-config.php` file will be in the site's root directory.
> Detect WordPress by configuration file

- cli/Valet/Filesystem.php
- cli/includes/helpers.php
- Adds helper function `quote ( $string, $quote_character = '"' )`
- Uses `quote()` on `$target` when running `symlinkAsUser($target, $link)`
> Fix spaces in path when using 'valet link'

- cli/Valet/Ngrok.php
- cli/Valet/Site.php
- cli/drivers/ContaoValetDriver.php
- cli/includes/compatibility.php
- cli/includes/helpers.php
> Use strict comparisons

- cli/drivers/WordPressValetDriver.php
Common in plugins unfortunately.
> Populate SERVER_ADDR to avoid undefined index notices in WordPress

- cli/includes/helpers.php
After doing a `composer global update` today, I started receiving PHP Fatal Errors when running valet like this: 
```
PHP Fatal error:  Cannot redeclare tap() (previously declared in /Users/nateritter/.composer/vendor/illuminate/support/helpers.php:811) in /Users/nateritter/.composer/vendor/laravel/valet/cli/includes/helpers.php on line 123
Fatal error: Cannot redeclare tap() (previously declared in /Users/nateritter/.composer/vendor/illuminate/support/helpers.php:811) in /Users/nateritter/.composer/vendor/laravel/valet/cli/includes/helpers.php on line 123
```
To fix this, I simply wrapped the helpers.php tap() method in a function_exits conditional and voila.  Thought I'd share.
> Helper tap method conflict fix

- cli/drivers/ValetDriver.php
Static files with uppercase extensions are being served with the mime-type 'application/octet-stream' because the keys in the mime-types array are all lowercase. This patch converts the static files' extensions to lowercase so static files are served with the correct 'Content-Type'.
> Convert static file path extension to lowercase

- cli/valet.php
fix for the empty $name issue in unlink command, e.g.    
The [] symbolic link has been removed.
> unlink command: fix for the empty $name issue 

- cli/drivers/SymfonyValetDriver.php
This pull request adds support for Symfony versions which are lower than 3.0, by the way.... awesome work for **valet** - it work's like a charm :)
> Added valet support for Symfony < 3.0

- cli/drivers/WordPressValetDriver.php
When attempting to access `/wp-admin` while unauthenticated, WordPress redirects to login `/wp-login.php`. After completing the login form you are then redirected to `wp-admin` instead of `wp-admin/` which causes issues with all the links in the admin until you add the trailing slash.
> WordPressValetDriver: Redirect wp-admin to wp-admin/

- cli/drivers/ValetDriver.php
- cli/drivers/require.php
- drivers/DrupalValetDriver.php
This driver adds support for Drupal 7 and 8.
> Drupal 7 & 8 Driver

- cli/Valet/Brew.php
- cli/Valet/PhpFpm.php
- tests/BrewTest.php
Now that homebrew allows for installation of PHP 7.1 (albeit beta-1), if one is using php71 valet won't install (gives "Unable to determine linked PHP").
> Add basic changes to allow php71

- cli/Valet/Configuration.php
- cli/valet.php
Running `valet list` showed descriptions for everything except `secure` and `unsecure`.
> Add missing descriptions

- cli/Valet/Configuration.php
- cli/stubs/Caddyfile
- cli/stubs/SecureCaddyfile
- cli/valet.php
- tests/ConfigurationTest.php
This PR adds the option to view the Caddy access- and error-log using 
```valet server-log```
The both logfiles are stored in the ~/.valet/Log directory.
> Adds the option to view Caddy access- and error-log

- cli/drivers/BasicValetDriver.php
When serving basic PHP files, the include path may depend on DOCUMENT_ROOT. Set this server variable to improve compatibility with even more projects.
> Set DOCUMENT_ROOT correctly when serving index.php files.

- valet
This patch enables passing custom parameters like --region or -subdomain.
valet share --region=eu -subdomain=my_custom_domain
If you have a paid version of Ngrok the subdomain param is available, which is very handy when working with customers. Share the link once, instead of sharing a new random link every time you want your client to look at your progress.
> Pass parameters to ngrok

- cli/Valet/PhpFpm.php
- cli/stubs/Caddyfile
- cli/stubs/SecureCaddyfile
This pr updates caddy and php-fpm to use a socket instead of port 9000. I figured if we were going to do this in the most straight forward way I might as well do the work. If you have different requirements I'd be happy to change my pr.
See #157 for reasoning behind this.
> Use sockets instead of port 9000

- cli/drivers/BedrockValetDriver.php
This is the same as #96 but solves the problem with Bedrock driver.
When attempting to access `wp/wp-admin` unauthenticated, WordPress redirects to `wp/wp-admin` instead of `wp/wp-admin/` which causes issues with all the links in the admin until you add the trailing slash.
> Bedrock: Redirect wp/wp-admin to wp/wp-admin/

- .travis.yml
This makes it so that travis doesn't have to redownload the composer vendor files each time it runs. This helps prevent download inflation on packagist (Might be a negative 😄) and makes travis tests run a lot faster.
> Add composer cache to travis config

- cli/includes/helpers.php
Same problem we had with `tap` function...
````
PHP Fatal error:  Cannot redeclare retry() (previously declared in /Users/mac/.composer/vendor/illuminate/support/helpers.php:618) in /Users/mac/.composer/vendor/laravel/valet/cli/includes/helpers.php on line 98
Fatal error: Cannot redeclare retry() (previously declared in /Users/mac/.composer/vendor/illuminate/support/helpers.php:618) in /Users/mac/.composer/vendor/laravel/valet/cli/includes/helpers.php on line 98
````
> Adding function_exists to retry

- cli/Valet/Caddy.php
If a `.DS_Store` file winds up being created in the Caddy directory (which would happen if any files are added or removed from that directory via Finder), the `import` in the first line of the Caddyfile will pull it in; this causes Caddy's startup to fail silently with a `Parse error: Unknown directive ':80'` error, and Valet will appear to boot, but sites will not be accessible.
Any attempt to ignore that file in the `import` directive also causes Caddy to balk (unless I just didn't get my glob syntax right). The solution in this PR is to delete any `.DS_Store` files in `.valet/Caddy/` whenever Caddy tries to start or restart.
> Fix potential launch failure by removing .DS_Store file from Caddy directory

- cli/Valet/Brew.php
- tests/BrewTest.php
As brew no longer allows running itself as root, we need to run it as the current user. This resolves #221.
> Run brew list as user

- cli/includes/facades.php
- cli/includes/helpers.php
Composer's "hoa" package also has a global helper function named "resolve". I added a function exists check to prevent the error I was getting:
```
PHP Fatal error:  Cannot redeclare resolve() (previously declared in /Users/calebporzio/.composer/vendor/hoa/core/Protocol.php:1140) in /Users/calebporzio/.composer/vendor/laravel/valet/cli/includes/helpers.php on line 57
```
With one exception, that helper function is only used in tests. It seems Facades would break if this function was overwritten, so I took the liberty of using the Container facade directly in facades.php
Also, [other people online](https://laracasts.com/discuss/channels/laravel/laravelvalet-getting-error) have run into this issue - thanks!
> Fix potential resolve() helper function conflict

- cli/drivers/CraftValetDriver.php
Pull request adds basic (as per [the official guide](https://craftcms.com/docs/localization-guide#step-5-set-up-the-files)) localization (i.e. multi-locale) support for Craft CMS. Code contributions by @sjelfull and @danethomas, see #179 for discussion.
> Adds localization support to the Craft CMS driver

- cli/drivers/Concrete5ValetDriver.php
- cli/drivers/ValetDriver.php
- cli/drivers/require.php
This driver makes a defines the `CONCRETE5_ENV` environment variable available for use in concrete5 if one isn't set. We determine if it should serve by detecting the "/concrete/config/tests/base" directory as this directory exists in the widest range of concrete5 versions.
> Add a concrete5 driver that provides the environment

- cli/stubs/valet.conf
When retrieving the query string in your app, it's twice the value it should be.
For example I have a request like "/overview?page=1" when I use request()->server('QUERY_STRING') I get "page=1&page=1" instead of "page=1".
Removing the ?$querystring for the Nginx config in the rewrite directive fixes this.
> Fix for query string in PHP

- cli/stubs/valet.conf
This will prevent `Request Entity Too Large` errors when uploading files.
> Fix `Request Entity Too Large` error by adding client_max_body_size to config

- cli/drivers/CraftValetDriver.php
Sets `$_SERVER['PHP_SELF']` to equal `$_SERVER['SCRIPT_NAME']`, which fixes the issue described in #244.
> Fixes issue #244, where the Craft CMS admin panel is inaccessible

- cli/drivers/ValetDriver.php
This PR allows you to add a `SiteValetDriver.php` to your project root to be used for the driver.
This might be useful if the site is set up in a different way than the bundled drivers expect.
For example, Statamic allows you to localize your site by creating a separate index.php files, but you're free to place them anywhere - potentially inside subfolders. The bundled driver can't know where you've placed additional index.php files. 
Now I can drop a custom driver in the root and override the `frontControllerPath` logic.
```
<?php
class SiteValetDriver extends StatamicValetDriver
{
public function frontControllerPath($sitePath, $siteName, $uri)
{
// some custom logic...
}
}
```
Another usage example could be to support `public_html` (or whatever) instead of a `public` folder.
Not married …
> Support a custom driver on a per-site basis

- composer.json
Before it would install PHPUnit 6 which only has namespaced classes and doesn't support PHP 5.6.
> Lock PHPUnit version

- cli/valet.php
Occasionally I find myself in my projects directory and my reflex has been to type `valet open $dirname` to open a site in the browser.
This PR adds that ability. Saves a few keystrokes when you would have to cd into a directory to `valet open` it.
> Adds the ability to pass a directory to `valet open`

- cli/Valet/PhpFpm.php
- cli/stubs/nginx.conf
- cli/stubs/php-memory-limits.ini
- cli/stubs/valet.conf
- tests/PhpFpmTest.php
- tests/files/php-memory-limits.ini
- Sets `client_max_body_size 128M` in `http` section of `nginx.conf`  so it covers all configs
- Adds `php-memory-limits.conf` to `php-fpm` conf folder, to set `memory_limit`, `upload_max_filesize`, `post_max_size` all to 128M
(Updates #253 by moving config location to cover all, since #253 didn't cover secure configs, etc)
> Fix large-upload problems by setting PHP limits and Nginx max size

- cli/valet.php
This little tweak removes `.` (current directory) and `..` (parent directory) from `valet links` output.
e.g.
```
total 8
drwxr-xr-x   3 jerguslejko  staff  102  9 Dec 01:38 .
drwxr-xr-x  10 jerguslejko  staff  340  9 Dec 01:18 ..
lrwxr-xr-x   1 jerguslejko  staff   18  9 Dec 01:38 blog -> /Users/jerguslejko/code/blog
```
vs
```
total 8
lrwxr-xr-x  1 jerguslejko  staff  18  9 Dec 01:38 blog -> /Users/jerguslejko/code/blog
```
🌵
> Clean up `valet links` output

- cli/drivers/CraftValetDriver.php
Currently the Craft 3 Beta has the front controller stored in a `/web` directory; Craft 2 stored it in the `/public` directory.
As Craft 3 Beta has a `craft` cli bootstrap file, we can use this as our check in the `serves()` method. We can also use this to determine whether to load the front controller from the `/web` or `/public` directory.
> Add support for Craft 3 Beta

- cli/Valet/Nginx.php
Before restarting nginx it will execute:
```
sudo nginx -c /usr/local/etc/nginx/nginx.conf -t
```
which, on success, must return
```
nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful
```
And on fail vallet will tell
```
Nginx cannot start, please check your nginx.conf.
```
> Check nginx.conf for errors before restarting nginx

- cli/Valet/Brew.php
- cli/Valet/Nginx.php
- cli/Valet/PhpFpm.php
- tests/BrewTest.php
Give users some info while starting, stopping and restarting services:
> Show start & stop process info in terminal

- cli/valet.php
If valet is not yet installed we get all sort of errors on commands, like
So I thought we could just show this, while not installed:
> Forbid access to most commands if not installed

- cli/Valet/Site.php
When wildcard SAN certs were introduced https://github.com/laravel/valet/commit/f51959f7ec59f84e38c9031d121e63a3df2d2c15, a new `.conf` file was added to the Certificates directory. This file is not currently being filtered out during the `Sites#secured` method, and it's leading to some interesting behavior when running `valet domain <domain>` after you have secured at least one site:
😬 After switching domains about 8 times, this breaks Nginx's configuration, and you cannot access any sites through Valet until you delete all the configs. I don't know why, but I assume it's because there are too many/weird configs.
This PR filters out the extra file when building the URL list so this doesn't happen.
> Filter out .conf files when switching domains

- cli/drivers/ValetDriver.php
Contao 4.x is a symfony bundle/application. The symfony driver is currently loaded/checked before the concrete contao driver. In result, the contao driver never gets loaded, because the local contao installation gets handled by valets symfony driver, not the contao driver.
To fix this, the contao driver should always been loaded/checked before the symfony driver (more _specialized_ driver above the _general_ symfony driver).
> Fix contao driver never gets loaded

- cli/valet.php
Added `--secure` option for `valet link` command. This can save some time when people want to link specific folder to domain and then generate certificate.
> Secure option for link command

- cli/drivers/LaravelValetDriver.php
- cli/drivers/SymfonyValetDriver.php
- server.php
See #342 - this PR changes the rewriting of the `$_SERVER['HTTP_HOST']` variable in case of an Ngrok proxy.
The default behavior for the `LaravelValetDriver` remains unchanged (restoring the original `Host` value), but other drivers will now revert to standards-compliant behavior which leaves the `Host` header as-is. The `X-Forwarded-Host` can then be used to retrieve the hostname that was entered by the visitor, i.e. the `*.ngrok.io` hostname.
> Improved HTTP_HOST rewriting

- cli/stubs/secure.valet.conf
- cli/stubs/valet.conf
client_max_body_size does not propagate down from the http context into
the server context.
See this stack overflow for further details on the issue:
https://stackoverflow.com/questions/2056124/nginx-client-max-body-size-has-no-effect
This fix ensures that the max client body size is always the default
128mb as specified in nginx.conf.
> Fix 128mb max client body size for secured sites.

- cli/Valet/Brew.php
- cli/Valet/PhpFpm.php
Before this pull request we only supported PHP `5.6` - `7.1`. Now that `7.2` has an available RC and is installable via homebrew I believe we should add support for it.
> Add support for the PHP72 package

- cli/valet.php
Here we take the currently logged in user, and run the open command as that user instead of root. This ensures that your default browser choice works.
Steps to reproduce:
* cd into a directory that has a site
* Type "valet open"
Before patch:
Valet always opens Safari. The open command runs as root, so it doesn't read the local user's default browser preferences.
After patch:
Valet opens in your default browser. If that happens to be Safari still, that also works.
> Fix bug where the "valet open" command ignores your default browser choice

- cli/Valet/Nginx.php
Just a little typo fix I saw : There's 4 ellipsis dots at the end of the "Stopping ngnix" string.
> Fixed typo: two much dots in ellipsis

- cli/drivers/CraftValetDriver.php
Certain CraftCMS plugins (might) depend on the $_SERVER['DOCUMENT_ROOT'] variable being set.
> Add $_SERVER['DOCUMENT_ROOT'] to CraftValetDriver

- cli/drivers/LaravelValetDriver.php
The current check short-circuits too early, allowing the existence of a folder at $uri
to trigger a false positive. This verifies that the file at $uri is actually a file before
returning.
> Checks to see if file_exists *and* it's an actual file.

- cli/Valet/Site.php
Generate SHA-256 certificates as SHA-1 certificates, the current default, are deprecated and support for them will quickly be dropped by major browsers as documented here: https://blog.qualys.com/ssllabs/2014/09/09/sha1-deprecation-what-you-need-to-know
> Generate SHA-256 certificates

- cli/drivers/StatamicValetDriver.php
This PR provides support for the new way that statically cached files are handled in Statamic 2.6.
This also provides support for users to serve localized versions of their site in subdirectories. It uses a list of ISO3166 alpha-2 codes which covers most use cases.
eg. `mysite.dev/fr/`
For edge cases, developers can extend this driver in their `LocalValetDriver` and override `getLocales()` with the subdirectories/locales they need. They can also override `getStaticPath()` if they need static caching support for versions below 2.6.
> Statamic caching and localization support

- cli/drivers/BedrockValetDriver.php
Fix for Wordpress (Bedrock) as in #138
> Set SERVER_NAME variable for WordPress (Bedrock) driver

- cli/drivers/StatamicValetDriver.php
In my [previous PR](https://github.com/laravel/valet/pull/401), I added all the ISO3166 alpha-2 codes, which doesn't include `en`. You can also override the `getLocales` method in a LocalValetDriver if you need to add exceptions.
But, there a ton of people that like to use `en` if they don't use English by default. This PR just adds it to the list because its super common.
> Add en to locales

- cli/drivers/Magento2ValetDriver.php
Was getting the following:
```
a:4:{i:0;s:38:"DOCUMENT_ROOT variable is unavailable.";i:1;s:1058:"#0 /Users/simensen/Code/magento-cloud-blackfire-example/vendor/magento/framework/App/Http.php(181): Magento\Framework\App\SetupInfo->__construct(Array)
#1 /Users/simensen/Code/magento-cloud-blackfire-example/vendor/magento/framework/App/Http.php(213): Magento\Framework\App\Http->redirectToSetup(Object(Magento\Framework\App\Bootstrap), Object(Exception))
#2 /Users/simensen/Code/magento-cloud-blackfire-example/vendor/magento/framework/App/Http.php(137): Magento\Framework\App\Http->handleBootstrapErrors(Object(Magento\Framework\App\Bootstrap), Object(InvalidArgumentException))
#3 /Users/simensen/Code/magento-cloud-blackfire-example/vendor/magento/framework/App/Bootstrap.php(263): …
```
> Support for Magento Commerce (Cloud) applications that rely on DOCUMENT_ROOT

- cli/drivers/SculpinValetDriver.php
Modern Sculpin sites are closer to regular PHP projects. They use Sculpin as a dependency. They usually have a `source` directory so if `source` and `output_dev` both exist, there is a good chance it is a Sculpin project.
If you'd prefer changing how this is handled, let me know! I'm happy to change it. :)
> Enable support for modern Sculpin projects.

- cli/Valet/Site.php
Can't `valet links` other domain show https except `.dev`
Fixes #445
> Update valet links command to parse out https for non-.dev domains

- cli/valet.php
- server.php
This PR optionally enables a fallback site path for uncaught urls.
It adds a "fallback" command to the CLI:
It also adds the inverse command, "unfallback":
Example use case…
I'm developing a site locally on my Mac and I want to view it on my mobile device which is connected to the same LAN. I could run `valet share` from my site's local directory, but because ngrok is painfully slow where I live & work, I run `valet fallback` instead:
On my mobile device, I enter my Mac's LAN IP address and I am now viewing the site I was developing on my Mac. Yay! When I'm done, I run `valet unfallback` (or `valet unfall` because it sounds cooler) and the site I'm developing is no longer viewable by my mobile device:
Closes #440
> Fallback Site Path

- cli/Valet/Brew.php
- cli/Valet/Valet.php
- cli/valet.php
- tests/ConfigurationTest.php
Brings back the sudoer files, but now optional.
When they were removed: 
https://github.com/laravel/valet/pull/334/files
Addresses issues like https://github.com/laravel/valet/issues/446
One big question is whether this test actually does any good, since it just tests that the commands do what they do. `¯\(°_o)/¯`
Closes #446
Closes #198
Impacts #206
> Add 'trust' command

- .gitignore
- cli/drivers/CraftValetDriver.php
The previous method simply returned `web` if there was a file named `craft` in the $sitePath (which means we’re running Craft 3).
The problem is that many sites, especially upgraded ones, will be serving out of `public`. This is also in line with the default Forge/ServerPilot default dirs.
So we test to see if either `/web` or `/public` exist, and return them if so. Otherwise default to the current method.
> Craft driver web or public

- cli/Valet/Brew.php
Update supportedPhpVersions to include the new names used by homebrew now that the php packages have migrated to 'core'.   `php71` has become `php@7.1` etc
The new names are put at the front of the list to optimise the loops that use these collections.
Anyone who installs or updates 'homebrew php' from will start using the new packages names which breaks parts of valet.
> Update Brew.php - Homebrew\Core Package Names

- cli/Valet/Brew.php
- cli/Valet/PhpFpm.php
Previous versions of brew installed PHP like so:
```
/usr/local/opt/php71/bin/
```
Now they look like this:
```
/usr/local/opt/php@7.1/bin/
```
These changes just tweak the version check to remove `@` and `.` from the paths. So this should be backwards compatible with older installations as well.
*I was unable to get the tests running, but I applied these patches locally and went from not being able to install to a valid installation.*
> fix for new php versions/paths from php installed via brew

- cli/Valet/Brew.php
- cli/Valet/PhpFpm.php
- tests/BrewTest.php
Hello,
With previous code valet not found the new versions with `@` in name. Therefore valet not restarting these php versions.
Also unify the list of php versions.
> Unify php versions list. Fix deprecated homebrew/php

- cli/Valet/Site.php
This PR addresses these issues
https://github.com/laravel/valet/issues/390  
https://github.com/laravel/valet/issues/296  (import `~/.valet/CA/LaravelValetCASelfSigned.pem` to FF trusted authorities and all valet sites will be trusted)
https://github.com/laravel/valet/issues/460 (works when `curl https://mypage.test/ --cacert ~/.valet/CA/LaravelValetCASelfSigned.pem`)
as well as issue I found out while playing with it, namely that `unsecure` previously did not remove old certs from keychain (had tons of them) due to `security delete-certificate` not passing keychain parameter.
As the changes are only in one file it is easy to test them for those who use valet with master branch (`composer global require laravel/valet dev-master`) and are affected by this issue and cannot wait till this …
> adding CA to the created certificates

- cli/drivers/KirbyValetDriver.php
In version 3, there is no panel directory any longer, it's integrated in kirby proper.
This small changes prevents us from trying to load the /panel/index.php that doesn't exist.
> Support Kirby v3 as well

- cli/drivers/CraftValetDriver.php
As Craft 3 RC11, it is no longer necessary to route sites with base URI paths to separate index.php files. Craft will automatically detect URI segments that were meant to be part of the site base URI, and ignore them when routing the request.
https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#300-rc11---2018-02-20
> Craft driver optional separate index.php

- cli/drivers/DrupalValetDriver.php
Drupal 8 uses q in $_GET for autocomplete args, it shouldn't always be overwritten with uri if q is already set.
Issue #455
Fixes #455
> Drupal 8 autocomplete

- cli/includes/helpers.php
- tests/BrewTest.php
- tests/ConfigurationTest.php
- tests/DnsMasqTest.php
- tests/NginxTest.php
- tests/PhpFpmTest.php
- tests/SiteTest.php
Valet doesn't play well with others.
In its `helpers.php` file it registers a number of global functions without considering the landscape of the current environment. This leads to fatal errors being raised when Valet redeclares methods that already exist.
To remedy this issue, I've placed the helpers used by Valet in the `Valet` namespace.
> Move the helper functions into the Valet namespace

- cli/Valet/PhpFpm.php
On performing `valet install` the current version of valet will error due to deprecated taps, previous taps moved to `homebrew/homebrew-core`.
```
> valet install
Stopping nginx...
Installing nginx configuration...
Installing nginx directory...
Installing php71...
Error: homebrew/dupes was deprecated. This tap is now empty as all its formulae were migrated.
Error: homebrew/versions was deprecated. This tap is now empty as all its formulae were migrated.
Error: homebrew/php was deprecated. This tap is now empty as all its formulae were migrated.```
> Update the tap list, current taps deprecated.

- cli/valet.php
This PR fixes a bug introduced in #602 which namespaced all helper functions, but didn't import them in `valet.php`.
E.g.
```
PHP Fatal error:  Uncaught Error: Call to undefined function info() in /Users/aaemnnosttv/.composer/vendor/laravel/valet/cli/valet.php:234
```
> Add missing imports for helpers

- cli/Valet/Configuration.php
- cli/valet.php
Fixes #618
This now forces a migration of the 'domain' key to 'tld' in the config, to make it easier for upgraders from v2.0.0-2.0.12 to newer.
> Fix php errors from #241 (valet tld command)

- .gitignore
- cli/Valet/Configuration.php
- cli/Valet/DnsMasq.php
- cli/Valet/Nginx.php
- cli/Valet/Site.php
- cli/Valet/Valet.php
- cli/includes/helpers.php
- server.php
- tests/ConfigurationTest.php
- valet
> Move ~/.valet to ~/.config/valet

- cli/Valet/Configuration.php
This PR fixes the PHP errors reported in https://github.com/laravel/valet/issues/620#issuecomment-417365462 which were a result of merging #449 
From the tests I've been doing with both "old" and "new" locations of the config files, this PR seems to resolve those.
> Fix errors from relocation of config dir

- cli/valet.php
- valet
The `valet share` command relies on the `tld` command outputting only the TLD and not a status message ... much like was discussed in #620.
This removes the status message that was added with the recent tld update in #241. 
(Other alternatives were considered including special treatment if the "domain" alias was detected etc, but in the end I know that the preference is to keep the code simpler, and removing the status message felt like the best approach after all.)
> Remove extra message text from TLD output, for valet share cmd

- cli/includes/helpers.php
- cli/valet.php
Fixes #635 by detecting if the config directory is in the old location and moving it immediately when running any Valet command.
> Automatically move config after upgrade to v2.1

- cli/drivers/StatamicValetDriver.php
Statamic's Live Preview feature does a POST request to an item's actual URL with updated data so you can preview the item. If the item had already been statically cached, the same html file would load every time, and not reflect your changes.
We ship Statamic with sample config files for this situation. An htaccess for Apache, an nginx conf for Nginx, and this PR is the equivalent for Valet users.
> Only serve statically cached files on GET requests for Statamic

- cli/drivers/DrupalValetDriver.php
I've spotted an issue when using Valet with Drupal, that running functional tests are failing when Drupal is installed within a sub-directory like `web` or `docroot`. This situation is becoming more common the more that using Composer to manage Drupal projects. I've been testing this with a newly cloned version of https://github.com/drupal-composer/drupal-project with the Examples module (which contains some PHPUnit tests).
Default output:
```
There was 1 error:
1) Drupal\Tests\phpunit_example\Functional\PHPUnitExampleMenuTest::testLinksAndPages
Behat\Mink\Exception\ElementNotFoundException: Button with id|name|label|value "Log in" not found.
```
Within phpunit.xml, I've set `SIMPLETEST_BASE_URL` to be `https://drupal8-subdir.test` to match the domain name provided with Valet.
Using …
> Failing functional tests with Drupal in a sub-directory

- cli/drivers/ContaoValetDriver.php
This PR adds support for the `app_dev.php` front controller:
* `http://folder.test/contao/login` -> prod mode
* `http://folder.test/app_dev.php/contao/login` -> dev mode with profiler
> [Contao] Support the app_dev.php front controller

- cli/valet.php
In some cases of mixed older versions and configs, the 'tld' config entry was not set.
This now updates (sets) the `tld` config entry if it is not set.
> Sanity check for tld config

- cli/stubs/secure.valet.conf
- valet
Since the current TCP port 88 clashes with Kerberos, changing it to port 60 which IANA shows as unassigned, and other databases show as not being used in general practice.
Several alternates were researched, but show (although limited use, nevertheless possible) clashes with other systems, including ports 47, 81-90, 8080-8090, and 100. Various sources were referenced, and the overall conclusion is that 60 seems to be the safest and least likely to conflict.
Tested against a few limited firewall configs without issue.
Tested with both fresh new valet installs and an older install upgraded from 2.0.x.
> Change valet share to use port 60

- cli/Valet/Configuration.php
- tests/ConfigurationTest.php
On a fresh OSX install, the ~/.config/ dir doesn't always exist. 
This improves the installation process by checking and creating it if needed.
> Pre-create the parent .config dir if needed

- .travis.yml
This should speedup builds a bit and makes it more consistent with other Laravel libraries.
> Disable xdebug

- cli/Valet/Brew.php
- tests/BrewTest.php
I was getting a "502 Bad Gateway" error after upgrading to PHP 7.3. This seems to fix it for me.
The error message was:
```
connect() to unix:/Users/<user>/.config/valet/valet.sock failed
```
> Support PHP 7.3

- cli/Valet/Filesystem.php
`Filesystem::mkdir()` / `put()` always return void. So these `return`s are redundant and should be removed.
> Remove redundant return.

- cli/Valet/PhpFpm.php
When no homebrew-installed PHP version is found, Valet attempts to install one.
The old default was `php71`. This PR changes it to `php`, which will install the latest Homebrew PHP version.
The problem with installing an older version is that Homebrew no longer symlinks it automatically. Rewriting Valet to do the symlinking is a little more involved since we should check for "which" version to link, vs other versions installed, etc.
Simply changing the default to the primary supported PHP version allows Valet to rely on Homebrew symlinking it properly ... ie: currently that means it'll install PHP 7.3
This should resolve recent complaints in old issue #533 related to "new installs of Valet on a fresh OSX"
> Change default PHP install pkg to 'php'

- cli/Valet/Nginx.php
Resolves #725 
Homebrew has been removing options on all formulas, therefore specifying an install option breaks the install of Valet.
> Remove outdated option in brew install options

- tests/PhpFpmTest.php
Hi, I've changed a PHP keyword to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!
> Change PHP keywords to comply with PSR2

- cli/Valet/Site.php
Resolves issue identified in #654.
---
When running `valet secure`, generated `.crt` file is empty and site is not reachable.
From within Laravel site root:
```
$ valet secure
Restarting nginx...
The [site-name] site has been secured with a fresh TLS certificate.
$ cat ~/.config/valet/Certificates/<site-name>.test.crt
```
Without code change, `.crt` file is empty.
> Fix SSL Certificate creation

- .travis.yml
Fixes the failing tests.
The former approach of using `nightly` to grab the latest in-dev PHP version isn't working well now that the `nightly` build is an alias for 8.0 ... and 8.0 isn't resolving composer packages since most haven't tagged anything compatible with it yet.
So switching to `7.4snapshot` allows testing against the next announced PHP version set to release later this year.
> TravisCI - change nightly(8.0) PHP to 7.4snapshot

- cli/Valet/CommandLine.php
Passing a command as string is deprecated since Symfony 4.2. Since we don't have command available as array, we should use `Process::fromShellCommandline()` instead.
> Fixes deprecated Process argument passed as string

- cli/Valet/Site.php
Should always provide CAserial, but should only provide CAcreateserial if file does not exist. Should probably fix permissions issue mentioned in the comments when attempting to create certificate.
> Fix issue with CA serial params

- .travis.yml
Until it's stable we probably shouldn't be failing builds that run into glitches with the nightly snapshots.
> Allow TravisCI to fail on PHP7.4snapshot builds

- cli/drivers/ValetDriver.php
This PR searches directories inside `~.valet/Drivers` so that users can easily bring in custom drivers from other packages. 
Before:
Clone the directory and then copy CustomValetDriver.php into your ~/.valet/Drivers directory
After:
git clone https://github.com/DCzajkowski/DistValetDriver.git ~/.valet/Drivers/DistValetDriver`
> Recursively search for custom valet drivers

- cli/Valet/CommandLine.php
And also check whether the method exists, see Issue #763 which was caused by my previous attempt to fix a warning., which can be found here: #761
> Fixed warning on newer symfony/process versions

- cli/valet.php
This PR adds a `HOME` path to the list of potential autoloaders at the head of Valet's CLI file.
To work on third-party open source PRs, I use [franzliedke/studio](https://github.com/franzliedke/studio) (installed globally).
My `studio` workflow for Valet PRs is to…
- Clone `laravel/valet` locally
- Create a new PR branch (e.g. `new-pr-branch`)
- From within `~/.composer` run `studio load [path to local laravel/valet clone]`
- Open `~/.composer/composer.json`
- Update `"laravel/valet": [version]` to `"laravel/valet": "dev-new-pr-branch"`
- Run `composer global update laravel/valet`
After stepping through my workflow…
- Without this PR, `valet` exits as no autoloader path can be found.
- With this PR, `valet` boots normally as the `HOME` autoloader path is found.
I understand…
- This PR …
> HOME Autoloader

- cli/valet.php
This PR is submitted in response to @mattstauffer's recent tweet regarding @gahlawat's #548:
[<img width="591" alt="tweet" src="https://user-images.githubusercontent.com/1914481/55528457-a90b4400-56e8-11e9-9006-fafb8401c19a.png">
](https://twitter.com/stauffermatt/status/1113538473976324105)
By default, the `logs` command tails Valet's `/Log/nginx-error.log` file:
```
valet logs
```
To tail **custom** log files, add relevant `"logs"` key/path values to `~/.config/valet/config.json`…
```
{
"tld": "test",
"paths": [
"…"
],
"logs": {
"nginx-access": "/path/to/nginx-access.log",
"php-error": "/path/to/php-fpm-errors.log",
"dnsmasq": "/path/to/dnsmasq.log",
"etc": "…"
}
}
```
…then pass the relevant `"logs"` key when calling the `logs` command:
```
valet logs nginx-access
valet logs php-error …
```
> #548 Refinements ("valet logs" Command)

- valet
Fixes #321 where valet home path was getting set into /var/root folder
Creds to @Patistar
> Preserve user Home and env when calling sudo commands

- cli/drivers/DrupalValetDriver.php
This change fixes issues with using the JSON:API in Drupal.
> Add JSON:API support for Drupal

- cli/Valet/Brew.php
- cli/Valet/Valet.php
If you've previously run `valet trust` to allow valet to run without specifying `sudo` repeatedly or entering your password with various valet commands, recent updates to MacOS may give you a `sudo: sorry, you are not allowed to preserve the environment` response when trying to run those `valet` commands.
The fix is in updating the sudoers entry that `valet trust` creates.
This PR tells valet how to update the sudoers entry so that this message doesn't continue.
YOU WILL NEED TO RE-RUN `valet trust` IF YOU HAD PREVIOUSLY RUN IT, after installing this update, in order for this code change to have any effect.
(Technical explanation: the sudoers protections have become stricter, so we have to be more explicit that we do indeed want environment variables to flow through to the sudo user's …
> Fix "sudo: sorry, you are not allowed to preserve the environment" msg

- cli/valet.php
We require Collect@5.3 but sortKeys was introduced in 5.6.6. This small change avoids bumping up that dependency for a simple sort.
> Replace sortKeys with native ksort to avoid bumping Collect dependency

- cli/valet.php
Previously when checking if the Valet version in use was the latest,
you'd have to go to Valet repo on GitHub, find out that all the docs
were on laravel.com, go there, find the upgrade instructions, and then
upgrade.
This can be simplified by giving the user the option to view the link.
Sample output:
```
$ ./valet on-latest-version
Your version of Valet (2.3.3) is not the latest version available.
Upgrade instructions can be found in the docs: https://laravel.com/docs/valet#upgrading
```
Future potential improvements:
- Add option asking the user if they would like to have the docs opened for them (and open the page in their browser if they do want that)
> Add link to upgrade instructions in outdated version error message

- composer.json
While the "technical" underlying code hasn't changed much, the version number dependencies do create some challenges (ref #815). Hence, I think it's sensible to update the versions.
Tests appear to pass properly when updating to ^6.0 and thus far it runs happily in my environment.
> Add compatibility with global illuminate 6.0 pkgs

- cli/stubs/secure.valet.conf
- cli/stubs/valet.conf
Fixes #772
I've been using this config change since Aug 17, 2019, without any negative side-effects.
All Valet services continue to work properly, and Valet Share still works just as expected.
If someone were to have a challenge with it, there's an easy downgrade: just remove the `127.0.0.1:` from these files, and run `valet tld test` to rebuild the individual site configs. Or just manually edit the `~/.config/valet/Nginx` site file manually.
> Improve security by listening on 127.0.0.1 only

- server.php
To support smarter detection of static-file detection and allow Valet to mutate the URI for externally-hosted assets (save bandwidth and local storage etc), detecting any custom-inserted environment variables needs to happen slightly sooner in the execution cycle.
Discovered this issue when troubleshooting #729 and #247. While they have other workarounds, this PR simplifies things, and potentially makes custom drivers slightly easier too ... when the use-case applies.
> Fire the .valet-env environment var detection earlier

- cli/stubs/secure.valet.conf
This is a very small addition that allows sites running on valet to test out preloading static assets.
However, `http2_push_preload` was not added into NGINX until 1.13.9 (released February 20th, 2018) which would mean this directive breaks secured sites on any older version of NGINX.
Figured this could be merged into the next major release?
> Allow http2 server push for secured domains [BREAKING]

- cli/stubs/fastcgi_params
- cli/stubs/valet.conf
These larger buffer sizes accommodate larger requests that are often complained about in Valet support issues.
These updates are inspired by common configs in Homestead.
I've been using these in my local Valet config for 4+ months, without any negative side-effects.
> Increase nginx buffer sizes in dev

- cli/stubs/nginx.conf
Increases domain name length support in Valet per #543 and #808
These are the same settings used in Forge.
> Allow for longer domain names

- cli/stubs/secure.valet.conf
- cli/stubs/valet.conf
A long-requested adjustment to Valet is to bypass the logging of robots.txt and favicon.ico hits. Particularly when keeping an Ngrok session alive.
This update is consistent with default logging settings in Forge.
> Turn off logging of hits to robots.txt and favicon.ico

- cli/Valet/Site.php
- tests/SiteTest.php
> Check for tld on end of certificate path to support multi segment tld's

- cli/Valet/Site.php
- cli/valet.php
- tests/SiteTest.php
Feature to provide functionality requested in #799 
Added under a separate command to be used alongside 'links' for only parked paths.
I left Site::getLinks as I wasn't sure if I should just replace it's usage with the newly added Site::getSites, I can do if that would be better.
> Add 'parked' command to show all sites which have been parked

- cli/stubs/secure.valet.conf
- cli/stubs/valet.conf
The `fastcgi_split_path_info` directive is ineffective in this NGINX configuration.
More @ https://github.com/laravel/docs/pull/4867
> fastcgi_split_path_info location regex fix

- cli/Valet/Site.php
- tests/SiteTest.php
When I added the parked command I forgot about non directory paths, I only noticed this today when a .DS_Store file was created in the directory and showed up in the parked output.
This fix filters out the sites by ensuring the path is a directory.
> Ignore parked paths that are not directories when getting sites

- cli/Valet/Site.php
Process `4.4.0` changed command-line parsing by being more aggressive with substitutions, causing our intended literal `"$NF"` to throw an exception.
https://github.com/symfony/process/compare/v4.3.8...v4.4.0#diff-9a01fc0e340da4c3f1e4a16029a63977R1644-R1653
The change made in this PR still functions correctly on both Process `4.3.8` and `4.4.0`. (I watched it update Keychain correctly, as well as generate the certificates in Valet's folders.)
Fixes #810 
Fixes #842
> Symfony/Process 4.4.0 compatibility

- composer.json
For compatibility with current symfony release updates
> Allow support for symfony/process 5.0

- cli/Valet/Site.php
Another issue I saw, this with duplicate site names.
Currently a linked site takes precedence over a parked site so it shouldn't be shown under 'parked' as it will never be served.
This also fixes an issue if you have multiple parked directories, the later parked ones would overwrite the previous if they share a site name, I've reversed this.
> Do not show sites in parked if they would not be served

- cli/valet.php
Previously `valet uninstall` would just shutdown the `nginx` service.
This PR also stops `PHP` and gives a bunch of instructions on how to do a (nearly) clean uninstall of most Valet dependencies.
And also some troubleshooting tips.
> Add detailed valet uninstall instructions

- cli/Valet/Site.php
- cli/valet.php
This PR allows passing `--all` to `valet unsecure` to have it remove all certificates from all Valet configs AND from the MacOS Keychain.
This effectively cleans up certificate fragments or broken configs, and can help with troubleshooting.
> Add --all parameter to valet unsecure command

- cli/valet.php
When switching to older PHP versions there may be a composer package dependency conflict. This PR adds a note to consider running `composer global update` to update those dependencies. It's only a comment since not all changes in PHP version will require running the update.
Fixes #822
> Add comment to consider running composer global update after switching php version

- composer.json
Since we require PHP > 5.6 there's no need to support symfony/process 2.x 
However, symfony/process 4.x requires minimum PHP 7.1 so have to retain 3.x for now if we wish to support PHP 7.0 or older without complications.
As referenced in #845 comments.
> Drop unnecessary symfony/process 2.x support

- cli/Valet/Nginx.php
While since #268 valet has been checking nginx configs for errors when starting/restarting, the captured errors are never displayed if there is a failure because it's being run using `quietly()`. 
This PR causes the errors to pass through to the console so we can more readily understand why nginx may not be starting or not serving properly.
> Display nginx config errors on start

- cli/Valet/DnsMasq.php
- cli/valet.php
While it's rare that the dnsmasq won't be started, it feels incomplete to not include the service when starting/restarting valet, since valet depends on it.
> Include dnsmasq in valet start/restart command

- cli/stubs/secure.valet.conf
Replaces and closes #575 ... for reasons described there.
I've been using this for a couple months without issue. (Granted, I don't leave valet share running for extended periods.)
> Set robots nofollow for all valet share traffic

- cli/Valet/Site.php
Fixes issue where certificates fail to be generated when there is a space in the certificate file path
Closes #862
> Cater for filepaths with spaces

- cli/Valet/Ngrok.php
- cli/valet.php
Ngrok Pro plans allow multiple processes, which means you could be serving several sites simultaneously. This PR allows Valet to correctly identify amongst the active ngrok process URLs.
Fixes #145
> Fix auto-detection amongst multiple ngrok processes

- cli/Valet/PhpFpm.php
- cli/stubs/etc-phpfpm-valet.conf
This allows the valet FPM pool configuration to stand separately from the default config.
This benefits troubleshooting, makes customization of FPM workers and other settings easer
and allows for easier uninstallation.
(Note: existing Valet installs will have had their PHP `/usr/local/etc/php/7.4/php-fpm.d/www.conf` files already altered by Valet. It will be best to restore this file to the default version installed by PHP to prevent duplicate FPM pool instances that conflict with each other. 
Or, simply delete the `www.conf` file.)
> Move PHP-FPM pool config to separate valet-specific file

- cli/Valet/DnsMasq.php
- cli/stubs/etc-dnsmasq-valet.conf
- tests/DnsMasqTest.php
Dnsmasq allows use of a common config folder, much like nginx and php do.
This PR changes Valet's default config to empower this feature.
This will make for easier troubleshooting
... and easier customizing (such as dropping in a custom logging config, additional TLDs, alternate DNS resolvers, etc)
> Use custom dnsmasq.d folder for easier config and support

- cli/Valet/Brew.php
- cli/Valet/Configuration.php
- cli/Valet/DnsMasq.php
- cli/Valet/Nginx.php
- cli/Valet/PhpFpm.php
- cli/Valet/Valet.php
- cli/valet.php
`valet uninstall` only displays information about how to manually uninstall and clean up after Valet.
This PR adds a `--force` parameter, which will forcefully remove Valet and the Homebrew services it installs, as well as clean up the config files and log files.
But for a few post-uninstall composer dependencies, cleanup is very thorough.
This brings idempotency to both `valet install` and `valet uninstall --force`
(There may still be edge cases where other Homebrew or composer packages might create interference with install/uninstall, but this makes things much easier to self-troubleshoot.)
> Allow Valet to uninstall itself

- cli/Valet/Ngrok.php
Thanks to the generosity of Alan at Ngrok, I've been able to do some additional testing with temporary added features.
Turns out #864 was incomplete. This PR now also loops through the default endpoints in order to find a process matching the passed domain.
Ref: #864
Ref: #145
Also supercedes and Closes #869 and Fixes #868 the same way #869 proposed.
> Part 2: Fix auto-detection amongst multiple ngrok processes

- cli/scripts/fetch-share-url.sh
- valet
This PR allows passing a specific domain name to `valet share` in order to have the app be served for that domain.
Now how it works is this:
- **(NEW)** if a domain name is passed, it checks whether it matches a link (which would be required for multiple domains served by same app project), and uses that
- if a domain name is NOT passed, it looks up any links for current directory, and uses the first found link
- else falls back to current project foldername
It also still allows passing through custom ngrok parameters if desired (ref: #112), as either the 2nd parameter (no domain name passed) or **(NEW)** 3rd parameter
Fixes #537
> Allow valet share to support multiple domains from same app

- valet
Enable the possibility to pass more than one argument to ngrok.
before this patch, it was not possible to pass more than one argument beginning with --.
now you can add something like this:
valet share --region=eu --authtoken=tokenstring
before this patch, only the first arg --region was used
> Enable multiple ngrok arguments from command line

- cli/drivers/ValetDriver.php
This leverages the existing `.valet-env.php` file capability, but just adds the Valet Home directory as a fallback-lookup location.
So, now Valet will check for `.valet-env.php` in:
- the current project folder
and if not found, then fallback to:
- `~/.config/valet/`
As discussed at https://github.com/laravel/valet/issues/789#issuecomment-565112046
Fixes #789
> Allow for global environment variables to be configured.

- cli/stubs/etc-phpfpm-valet.conf
The default FPM stub was overriding related settings, making customization more complex.
Commenting out the overrides so they can be used only if specific FPM settings need to supercede CLI settings.
Fixes #884
> Comment out memory limits so other configs take precedence

- tests/BrewTest.php
Replaces and closes #564
(TL;DR ... updates version numbers, adds tests for newer versions, rearranges some assertions so the `@` syntax/naming appear first since they're more contemporary syntax)
> Modernize PHP unit tests

- cli/stubs/etc-phpfpm-valet.conf
PHP configs no longer support `#` for comments. Must use semicolons `;`.
Otherwise PHP may not start, and may show a confusing error in logs: `value is NULL for a ZEND_INI_PARSER_ENTRY`
Updates #885
> php config comments must only use semicolons, not hash symbols

- cli/valet.php
Sometimes all we just need is to restart nginx or php-fpm during development. so having a way to restart a specific service saves some time instead of waiting for dns-masq, php and nginx to restart
> Allow start/restart/stop single service

- cli/Valet/Brew.php
- cli/Valet/PhpFpm.php
- cli/valet.php
Fixes #756
Previously if `php` was installed as just `php` (the default Homebrew alias), Valet would not detect **_which_** PHP version was actually installed, and therefore `valet use` might do incorrect or unnecessary installations/links/etc.
NOTE: This does NOT "convert" existing `php` alias to a numbered version. It merely accepts it as-is, but notes its version in an attempt to avoid extra installations.
**NOTE: Specifally tested with PHP 7.4 and 7.3. No promises about old 5.6, etc aliases.**
> Detect running php when no version constraint specified with use command

- cli/valet.php
While `valet trust` enables (creates) sudoers entries, there was no cleanup/removal option for this, apart from complete forced uninstall of Valet.
This adds `valet trust --off` so that the sudoers entries can be removed from Valet CLI.
> Add --off option for valet trust command

- cli/Valet/DnsMasq.php
- tests/DnsMasqTest.php
Previously we would leave old tld stubs around; while it's harmless, it's less tidy.
> Cleanup old tld refs when switching tld or uninstalling

- cli/valet.php
- server.php
After running `valet directory-listing on` if a URI points to a directory that exists, but the requested file cannot be found in that directory, a directory listing will be displayed.
A 404 will still happen if the project directory cannot be found.
Running `valet directory-listing off` makes a 404 display (without a listing) if the requested file cannot be found.
Supersedes and Closes #349 and Closes #587
> Adds a directory-listing setting for dev convenience

- cli/stubs/etc-phpfpm-valet.conf
- cli/stubs/nginx.conf
- cli/stubs/php-memory-limits.ini
- cli/stubs/secure.valet.conf
PHP's default is 128M, but it's becoming common practice to set the value to 512M in dev and production
Plus, currently homestead sets it to 512M as well.
(Note: Only takes effect after running `valet install`, or when `valet use php@X.Y` installs a new X.Y PHP version.)
Also closes #914
> Increase default PHP memory_limit to 512M

- composer.json
This will allow users to install this package with `laravel/vapor-cli`.
This is needed for the following scenarios:
```
composer global require laravel/valet
composer global require laravel/vapor-cli # fails
```
```
composer global require laravel/vapor-cli
composer global require laravel/valet # fails
```
> chore(deps): allow laravel/container:^7.0

- cli/Valet/Site.php
- cli/stubs/nginx.conf
- cli/stubs/proxy.valet.conf
- cli/valet.php
- server.php
- tests/SiteTest.php
- tests/fixtures/Proxies/Nginx/not-a-proxy.com.test
- tests/fixtures/Proxies/Nginx/some-other-proxy.com.test
- tests/fixtures/Proxies/Nginx/some-proxy.com.test
Provides helpers to create an Nginx proxy site for the specified host. 
Useful for `docker`, `vessel`, `mailhog` etc, so that both Valet and those other services can co-exist on the same machine. 
(In the case of docker, proxying avoids the problem where Valet and Docker want to share port 80, which is not allowed.)
(In the case of a service like mailhog, it already intends to run on a different port; but proxying allows this to be given a name that Valet recognizes and can serve quickly and easily.)
Adds 3 new commands:
`valet proxy [domain] [host]`  -- generates a proxy config file (see example below)
`valet unproxy [domain]` -- removes a proxy config file
`valet proxies` -- gives a list of proxies Valet is aware of
eg: 
`valet proxy docker http://127.0.0.1:8080` creates a config file …
> Add proxy site-handling commands

- cli/Valet/Diagnose.php
As discussed in https://github.com/laravel/valet/pull/938, this PR filters the `Launch*` commands to only show `homebrew`-related output.
Let me know if there's anything else!
> Filter Launch* commands output in "diagnose" command

- cli/stubs/proxy.valet.conf
- tests/fixtures/Proxies/Nginx/some-other-proxy.com.test
- tests/fixtures/Proxies/Nginx/some-proxy.com.test
The stub we used for normal usage as it relates to favicon.ico and robots.txt may not be appropriate for proxies. I'm seeing some weird behavior. I'm not even sure what the current configuration *does*, exactly, but if I remove them entirely Nginx forwards all requests to the proxy which is what I expected.
If someone has a better idea I'd be up for it. :) Otherwise, I think this probably fits better with the intent of the proxies.
> Stops interfering with favicon and robots for proxies

- composer.json
You all seem to be pretty good about updating cutting new releases and updating version numbers quickly, but I thought it would be nice to allow people to target `@dev` more easily (like `^2.10@dev` or something).
> Alias dev-master to 2.x-dev

- cli/valet.php
Sometimes I find myself wondering how to un-park a folder, and it takes me awhile to find `forget` in the list.
Adding `unpark` as an alias may be helpful.
> Add 'unpark' alias to 'forget' command

- cli/drivers/KirbyValetDriver.php
Kirby 3 now supports keeping site files above webroot. This PR adds support for it in Valet.
This driver has been tested with Kirby 2 and Kirby 3. Both versions are still supported by the same driver.
> Add support to setup Kirby above webroot

- cli/valet.php
Neither I nor the test suite have run into this so far, but @drbyte found this error while trying out #987, so I guess it doesn't hurt to change this since the behavior should be exactly the same. For reference, see https://github.com/laravel/valet/pull/987/files#r516814667
> Fix symfony default value error

- cli/Valet/Site.php
When we added the `proxy` feature in https://github.com/laravel/valet/pull/913 we inadvertently broke the `tld` command.
It was concatenating old+new tld when searching for existing configs, thus it couldn't find the correct file, which triggered the reported error.
Fixes #984 Thanks @kupoback for reporting it.
This PR fixes the lookup by allowing the correct intended lookup tld to be passed in. It also checks that the file exists before trying to read it.
Also fixed the proxy config cleanup done during a tld change (it wasn't rewriting all variants of the old tld, thus leaving them (and nginx) broken).
> Fix file_get_contents() error in tld command

- server.php
This will let us configure the various tunnel services online using pattern based matching.
Examples (not included in code):
`valet/config.json`
```json
{
"tunnel_services": [
".serveo.net",
"-*.localhost.run",
"-*-*-*-*.sslip.io"
]
}
```
This will support [serveo.net](https://serveo.net), [localhost.run](http://localhost.run) & [sslip.io](https://sslip.io).
It also supports nip.io's "dash" notation which wasn't possible before.
Don't have to rely on ngrok limitations since we can use one of these services with a custom subdomain and still be able to connet to valet/project.
> Make tunnel services configurable

- valet
This is a workaround to fix #904. Root cause is VSCode yielding the wrong output for `logname` when launched from the Dock / Spotlight / Finder _(see microsoft/vscode#96463)_. This bug in VSCode prevents `valet share` from working properly, when invoked from VSCode's terminal.
This workaround makes `valet share` work properly again in that case: when relaunching valet using `sudo` it will take in the current`$USER` and pass it in as an environment variable. This (overridden) environment variable is then used when launching `ngrok`.
> Pass USER as envvar when relaunching valet using sudo. Fixes #904

- cli/Valet/Brew.php
- cli/Valet/Diagnose.php
- cli/valet.php
- tests/BrewTest.php
`brew list` does not support TTY. So a raises a warning or error when used with pipe.
This PR solves the above situation.
Ex) 
```
❯ /opt/homebrew/bin/brew list | grep php
Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.
```
```
❯ /usr/local/bin/brew list | grep go
Warning: Calling `brew list` to only list formulae is deprecated! Use `brew list --formula` instead.
go
```
[Homebrew/brew#8851](https://github.com/Homebrew/brew/pull/8851)
[Homebrew/brew#8229](https://github.com/Homebrew/brew/pull/8229)
> Update brew list command to remove deprecation warning

- cli/Valet/PhpFpm.php
- cli/stubs/etc-phpfpm-error_log.ini
- cli/stubs/etc-phpfpm-valet.conf
Point PHP-FPM error_log to user directory
Old:  `/usr/local/var/log/php-fpm.log`
New: `~/.config/valet/Log/php-fpm.log`
(We already put `~/.config/valet/Log/nginx-error.log` in this same directory.)
This avoids ARM Mac differences in directory paths (eg: `/usr/local/` isn't a default anymore).
It also makes it easier for the User to find/access these logs.
Addendum to #992 discussion at https://github.com/laravel/valet/pull/992#pullrequestreview-533730869
> Point PHP-FPM error_log to user directory

- cli/Valet/Diagnose.php
Including the linked resolv.conf helps with troubleshooting situations where dns appears to not be working.
(Mostly the goal is to determine whether a conflicting entry is listed too early, or if the localhost is not listed first when others are present.)
> Include resolv conf in diagnose command

- cli/Valet/Brew.php
Specify 8.0 as latest PHP version
This is used mainly for new installs
> Specify 8.0 as latest PHP version

- .github/workflows/tests.yml
- .gitignore
- cli/stubs/etc-phpfpm-error_log.ini
- composer.json
- phpunit.xml
- tests/BrewTest.php
- tests/ConfigurationTest.php
- tests/DnsMasqTest.php
- tests/FilesystemTest.php
- tests/NginxTest.php
- tests/PhpFpmTest.php
- tests/SiteTest.php
Update test suite to phpunit 9.5 syntax
Refactored to use polyfill for older PHP versions via `yoast/phpunit-polyfills`
Note: this includes 2 important differences from usual phpunit test suites:
- instead of extending `PHPUnit\Framework\TestCase` we extend `Yoast\PHPUnitPolyfills\TestCases\TestCase`
- instead of handling fixtures via `setUp()` and `tearDown()` we use `set_up()` and `tear_down()` respectively
----
Comment regarding formatting: I chose to use the FQDN in the `extends` syntax of the class declaration instead of using `use` so that it is more quickly apparent that we're doing something slightly different than usual phpunit syntax, particularly in regards to the set_up() / tear_down() methods that appear immediately following the `extends` line.
----
IMO this closes #1002
> Update test suite to phpunit 9.5

- cli/Valet/Brew.php
- cli/Valet/Diagnose.php
- cli/Valet/PhpFpm.php
- cli/includes/helpers.php
- cli/valet.php
- tests/BrewTest.php
- tests/PhpFpmTest.php
Improvements to "valet use" command
- `valet use` can now display the currently-linked PHP version, for quick inspection
- properly detects if the requested version is already installed, and skips re-installing/re-starting/re-configuring
- allows `--force` to re-configure anyway
- smarter treatment of short 'php' name when it's aliased to another specific installed version
All in all, should be faster and a little more user-friendly.
> Improvements to "valet use" command

- cli/Valet/Valet.php
- cli/valet.php
Fixes #1023
Ref #992
/cc @jasonvarga
> Fix valet bin dir linking for ARM / M1 macs

- server.php
I don't know exactly since when my issue exists but I believe #997 has something to do with it. If I have 'parked' my `~/PhpstormProjects` directory filled with Laravel projects and have a linked directory inside one of those Laravel projects as a subdomain the parked directory is used instead of the linked directory. This PR prevents that.
To be clear:
```
cd ~/PhpstormProjects
valet park
cd ~/PhpstormProjects/project/subdomain
valet link subdomain.project
```
Then `subdomain.project.test` should link to `~/PhpstormProjects/project/subdomain`, but now it links to `~/PhpstormProjects/project`. After this PR is merged it links to `~/PhpstormProjects/project/subdomain`.
> Site path found, break from loops

- cli/Valet/PhpFpm.php
When switching PHP versions the valet.sock file may not be removed if the linked PHP process doesn't get shut down properly. This can happen when Homebrew switches default `php` version aliases and if one has started multiple homebrew PHP instances under different permission levels or different users.
This patch merely forces the .sock file's removal when switching versions. 
In very rare cases a filesystem lock may prevent the file's proper removal, in which case a reboot might be required.
To prevent these issues, keep Homebrew up-to-date by running `brew upgrade` on a regular basis (weekly is good).
Fixes #1010
> Force removal of orphaned valet.sock file

- cli/valet.php
Related: https://github.com/laravel/valet/issues/790#issuecomment-765559963
Changing from `info()` to just `output()` avoids ANSI char output for color display (which Vercel Hyper is misinterpreting), and this particular line doesn't "need" colored output particularly.
> Fix issue with `valet share` on Hyper

- cli/Valet/Configuration.php
- cli/Valet/Diagnose.php
- cli/Valet/DnsMasq.php
- cli/Valet/Nginx.php
- cli/Valet/Site.php
- cli/includes/helpers.php
- cli/stubs/ifconfig.plist
- cli/stubs/loopback.plist
- cli/stubs/proxy.valet.conf
- cli/stubs/secure.valet.conf
- cli/stubs/valet.conf
- cli/valet.php
- tests/DnsMasqTest.php
- tests/NginxTest.php
- tests/SiteTest.php
Provides helper to change the loopback address used by Nginx and Dnsmasq.
Useful for `docker`, use a custom loopback address gives the ability to resolve hosts from both host side and container side. You may alias your loopback interface using a [private ip address](https://en.wikipedia.org/wiki/Private_network).
Adds one new command:
`valet loopback [address]` -- get or set the loopback address
eg:
`valet loopback` results in 127.0.0.1 (default value)
`valet loopback 10.254.254.254 && valet loopback` results in 10.254.254.254
--
Docker DNS explanation : [https://williamhayes.medium.com/local-dev-on-docker-fun-with-dns-85ca7d701f0a](https://williamhayes.medium.com/local-dev-on-docker-fun-with-dns-85ca7d701f0a)
--
Get it working:
- create a loopback alias using `sudo ifconfig lo0 alias …
> Add loopback command

- server.php
Closes #1032
This PR reverts the changes from #1018 and fixes the problem with subdomains described in #1032.
The "breaking" change was in [server.php#L144](https://github.com/laravel/valet/blob/master/server.php#L144)
```php
if (strtolower($file) === $domain) {
$valetSitePath = $path.'/'.$file;
break;
}
```
The `break` statement stopped the execution of the loop too early, as `$domain` is not what we are looking for at this very moment, when using a linked subdomain.
I actually was able to reproduce the problem @mrk-j described in #1018 too and solved this by re-adding his outer break statement, but removing the early breaks. 
So, this should fix both problems described in #1018 and #1032.
> Fix subdomains pointing to root path

- .gitattributes
https://git-scm.com/docs/gitattributes#_marking_files_as_binary
> Git usually guesses correctly whether a blob contains text or binary data by examining the beginning of the contents. However, sometimes you may want to override its decision, either because a blob contains binary data later in the file, or because the content, while technically composed of text characters, is opaque to a human reader.
> Add `-diff` for binary file.

- cli/Valet/Brew.php
- tests/BrewTest.php
This is intended to assist with avoiding having competing non-root instances of valet dependency services running due to userland use of brew CLI commands.
Now, when running `valet stop` or `valet restart` it will (silently) attempt to stop the non-root instance (ignoring any errors thrown), before stopping (and/or starting) the sudo/root instance which is normally used.
(Though obvious, I'll point out that this only applies to services Valet manages.)
Fixes #1057
> Stop non-root homebrew services during restarts

- server.php
I just updated my local Valet installation, and it looks like the fix implemented in #1040 does not work for me. After putting some debug `var_dump`s in the `server.php` file in the `get_valet_site_path` function - in the loop and right before the return statement - it gave me the following output when trying to access `a.domain.test`:
```
// -> /Users/stidges/.config/valet/Sites/a.domain
// -> /Users/stidges/.config/valet/Sites/domain
// -> RESULT: /Users/stidges/.config/valet/Sites/domain
```
I think this is caused by the root domain coming _after_ the subdomain, so it overwrites the `$valetSitePath`. 
This PR breaks out of the loop as soon as the `strtolower($file) === $siteName` statement passes, as you're sure to have an exact match at that point. This would still allow for a …
> Fix subdomain using root domain link

- cli/drivers/SymfonyValetDriver.php
- server.php
This PR fixes this issue #1071. (Closes #1071)
The problem was with the clear Symfony 5 project. Symfony in the `index.php` file requires `autoload_runtime.php`.  Going further the `autoload_runtime.php` contains the following line:
`$app = require $_SERVER['SCRIPT_FILENAME'];`. Currently this variable points to the `server.php` file from valet what causes the problems with the Symfony 5 projects.
I've set the "correct" SCRIPT_FILENAME path manually just before requiring the front controller in the `server.php`.
I've performed some tests and it seems it won't break non-Symfony projects.
> Set the $_SERVER['SCRIPT_FILENAME'] to the front controller path

- cli/valet.php
This extension to the functionality of the `valet use` command adds a check for a `.valetrc` file when no version is passed as an argument, which contains the PHP version for the project and works in a similar manner to the `nvm use` command in Node Version Manager to save developers time and avoid mistakes when working across projects that have different PHP version requirements.
e.g. `.valetrc` in a project root could contain:
```
php@7.3
```
When `valet use` is run without specifying a PHP version you could expect one of the following outputs:
**Unlinking the current version for the specified version**
```bash
Found '/Users/johnnyappleseed/Sites/example/.valetrc' with version: php@7.3
Unlinking current version: php@7.4
Linking new version: php@7.3
Updating PHP configuration... …
```
> Added ability to use a `.valetphprc` file with `valet use` in a project to define the required PHP version

- cli/drivers/BedrockValetDriver.php
All request to PHP files are directed trough index.php which results in a 404 when you try to access a php file directly. This is not always the desired behaviour.
Also described in #539
> Allow execution of custom PHP files in Bedrock projects

- cli/valet.php
Having to type out `valet on-latest-version` is a pain, and I can never remember the right command without looking it up.
This adds an alias for that command, `latest`:
```sh
$ valet latest
> Yes
```
> Add alias for on-latest-version

- cli/Valet/Brew.php
Set Brew PHP latest version to 8.1 as PHP 8.1 is released and command `valet use php@8.0` now sets 8.1 and it is impossible to set 8.0.
> Set Brew PHP latest version to 8.1

- cli/Valet/Site.php
- cli/valet.php
- tests/SiteTest.php
This pr is meant to overcome an issue in concerning Chrome v58 and up.
**Test the default setting**
1. Clean linked directories, `$ valet unpark`
2. Run without `expireIn` should go to default. `$ valet secure <my_laravel_project>`
3. See if Chrome is happy - yes it is - validity is set default to 368 days now.
**Test with a too high `expireIn`**
1. Clean linked directories, `$ valet unpark`
2. Run without secure, `$ valet secure --expireIn=730 <my_laravel_project>`
3. See if Chrome is not happy, throws same error `net::ERR_CERT_VALIDITY_TOO_LONG`
**Test with a lower `expireIn`**
1. Clean linked directories, `$ valet unpark`
2. Run with shorter `expireIn`, `$ valet secure --expireIn=120 <my_laravel_project>`
3. See if Chrome is happy.
**Extra test is done by checking Mac's Keychain Access …
> Add 'expireIn=' option and use in the openssl command

- cli/valet.php
Fixes issue described in https://github.com/laravel/valet/pull/1154#issuecomment-992900342
I just tested this multiple times and can confirm that making it `null` makes `valet secure` break nginx config, but making it `368` in the source code makes `valet secure` work as expected.
> Fix certificate generation

- cli/Valet/Ngrok.php
- cli/Valet/Valet.php
- composer.json
As commented on #1157, HTTPful contains some deprecated calls and replacing it with Guzzle is better.
> Replace HTTPFul with Guzzle

- cli/includes/helpers.php
#1050 introduced some small changes to allow Valet to be used in a non-CLI context.
One of the changes was to only define the constants used by Valet if they hadn't already been defined. Rather than checking each constant individually and defining it if required, it only checks if one of the constants has been defined and then defines them all if it hasn't been. That chosen constant was `VALET_LOOPBACK`.
Despite that PR being merged, when including Valet as a package within a Laravel application that is being served by Valet, I still see the following warnings about constants already being defined: 
I'm relatively new to Valet, but diving into the source, it looks like when a site is served through `/server.php`, the only two constants that get set are `VALET_HOME_PATH `and …
> Fix warnings when using Valet in non-CLI context

- .gitattributes
- cli/Valet/Diagnose.php
- valet
This PR adds an ARM binary for ngrok to support Apple Silicon MacBooks. Unfortunately this will add around 30MB to the repo so not entirely sure this is wanted...
For Dusk where we do something similar with the chrome driver binaries, [we opted to remove them in the next major version](https://github.com/laravel/dusk/pull/873) and to let the user explicitly install them during the install process. That way the repos stay small. I'm not sure if there's any interest in taking that approach? If so I can look into it maybe.
Closes https://github.com/laravel/valet/issues/1171
> Add ARM support for ngrok

- valet
The extra " in line 86 breaks the installer and valet commands
FIXES:
```
/usr/local/bin/valet: line 95: unexpected EOF while looking for matching `"'
/usr/local/bin/valet: line 97: syntax error: unexpected end of file
```
> Fix syntax error in ./valet

- cli/Valet/Brew.php
- cli/Valet/PhpFpm.php
- tests/BrewTest.php
- tests/PhpFpmTest.php
Before the change, when running `valet use` the code intended to stop currently running PHP services. But the `getRunningServices` method only returned non-root running services. As PHP services started by Valet are run using `sudo` (so running as root), they were not returned and subsequently not stopped.
This change is intended to fix the above and stop PHP services that are started by Valet on a PHP version switch.
Described the actual issue I was facing in https://github.com/laravel/valet/issues/1177 
A few notes on the implementation:
- I initially tried to make the change as small as possible, and tried to update the current command to be something like `{ sudo brew services list && sudo -u "cristian" brew services list } | grep started | awk '{ print $1; }'` i.e. basically to get …
> Stop root homebrew services on php version switch

- cli/Valet/Nginx.php
- cli/Valet/PhpFpm.php
- cli/Valet/Site.php
- cli/includes/helpers.php
- cli/stubs/site.valet.conf
- cli/valet.php
- tests/NginxTest.php
- tests/PhpFpmTest.php
- tests/SiteTest.php
This PR modifies #1198, which is an update of #1192.
In #1192/#1198, `valet.sock` is always used by the global Valet PHP version, and then Valet sets up `valet80.sock` etc. for versions of PHP that aren't used globally but are used by isolated sites.
This PR makes it so that every PHP version used by Valet, global or not, sets up a `valet{version}.sock` file, and the global version is set by simply symlink-ing `valet.sock` to the version-specific `.sock` file.
This PR:
- Makes that symlink change
- Catches some work I missed in #1192 to the syntax in valet.php
- Cleans up `normalizePhpVersion` with a regex from @fuelingtheweb; again should've just applied to #1192
- Drops the tests that were covering the old pre-symlink behavior
Bugs in testing:
> Update `valet.sock` to be a symlink to an existing `valet{version}.sock` file

- cli/Valet/Nginx.php
- cli/Valet/PhpFpm.php
- cli/Valet/Site.php
- cli/stubs/site.valet.conf
- cli/valet.php
- tests/PhpFpmTest.php
- tests/SiteTest.php
This pull request introduces an optional `--site` flag on the `valet use` command, that allows users to run multiple versions of PHP in parallel on different sites. 
Btw, I build this feature to solve my very own problem. I need to constantly switch between PHP versions, as I need to switch between old and new projects. This is being very handy for me. 
```bash
valet use php@8.0 --site=site.test
```
or pass the site directory's name
```bash
valet use php@8.1 --site=site2 
```
or `cd` into the site's directory then use `.` to use current directory:
```bash
valet use php@8.1 --site .
```
```bash
valet use default --site .
```
<details>
<summary>Here's a video showing this feature up and running</summary>
https://user-images.githubusercontent.com/13833460/152670301-d479a21e-c82c-443e-b732-f46 …
> Multiple/Parallel PHP Version Support for Valet

- cli/Valet/PhpFpm.php
- tests/PhpFpmTest.php
Previously Valet was disabling `www.conf` during the PHP version installation process. 
But [these lines of codes](https://github.com/laravel/valet/commit/eefc06b07f8ee57186ce898cacaaf33f9504d679#diff-d8e7b9c98bc6a045292f784be0d98860c26b463a1dd29f36256fed1d2ad62752L89) was probably deleted accidentally. Or intentionally? I'm not sure. 
Either way, I think bringing these lines back should fix https://github.com/laravel/valet/issues/1205.
1. Install a PHP version using `brew install php@x.x` or `valet use php@x.x` that is not present on the machine.
2. Homebrew would create a `/etc/php/x.x/php-fpm.d/www.conf` file automatically during the installation process.
3. That should create a conflict and would result in a 502 error in valet sites.
> Fix Homebrew PHP default www pools issue on Valet 3.0 alpha

- cli/drivers/DrupalValetDriver.php
This is related to issue https://github.com/laravel/valet/issues/771 which was fixed by https://github.com/laravel/valet/pull/705
Unfortunately, as [this comment in the PR shows](https://github.com/laravel/valet/pull/705/files#r284138311), this will break for anyone not using the default path setting for [Drupal's JSON:API module](https://www.drupal.org/docs/core-modules-and-themes/core-modules/jsonapi-module/api-overview), like me. In Drupal I changed the default `/jsonapi` path to `/api` and this broke Valet's integration.
Specifically, when making any API call to a JSON:API endpoint, I got the same error as in the original issue:
```
The following query parameters violate the JSON:API spec: 'q'.
```
In the original issue there was already [a fix …
> fix: Drupal JSON:API support for non-standard url

- cli/Valet/Brew.php
- cli/Valet/Nginx.php
- tests/BrewTest.php
As discussed in #1220, cleaning up after stopping Homebrew services that run as `root` is probably the best solution for now. This PR now causes permissions to be reset whenever a Homebrew service is stopped.
What's changed:
- Stopping any Homebrew service now restores the appropriate permissions for the Homebrew directories
- Stopping nginx now also happens via $this->brew (to avoid code duplication)
The tests were updated to reflect this change.
There is one thing I'm uncertain of — whether the group owner needs to be `wheel` or `admin`. Either is fine, so in these commits I opted to go for `admin`, since that seems to be the default group ownership Homebrew assigns by default.
> When stopping Homebrew services, restore original folder permissions

- cli/Valet/Brew.php
- cli/Valet/PhpFpm.php
- cli/Valet/Site.php
- cli/valet.php
- tests/BrewTest.php
- tests/SiteTest.php
- valet
This PR introduces 3 new valet commands.  These will help users to run PHP and Composer commands with isolated site's PHP version on the CLI. 
1. `valet php ...` will proxy PHP Commands with isolated PHP version
2. `valet composer ...` will proxy Composer Commands with isolated PHP version
3. `valet which-php` outputs the PHP executable path for a site. For isolated site it would output the isolated PHP executable path. But non-isolated site will just output the linked default PHP path. The other two commands are dependent on this one to find the PHP executable. 
<details>
<summary> 🔽 Video demonstration </summary>
https://user-images.githubusercontent.com/13833460/159581055-4c1b7494-feb5-420a-946f-f89512597cc3.mp4
</details>
Though the [original …
> PHP version isolation helper for command line

- cli/valet.php
This PR adds two enhancements: 
1. Running `valet isolate` (without specifying a PHP version) on a directory where there's a `.valetphprc` file is present, Valet would recognize that. 
2. Running `valet use` (without specifying a PHP version) on an isolated site directory would change global PHP version to that isolated version. 
Fixes #1209
Tests: I'm not sure how do we test codes from `cli/valet.php` yet. I would be happy to add tests if I can get some guidance.
> Isolation compatibility with .valetphprc

- cli/Valet/Site.php
- cli/valet.php
- tests/PhpFpmTest.php
- tests/SiteTest.php
Adds a new column to the `valet links` CLI command output to show which PHP is version running on each site. This gives users who run multiple sites with isolated PHP versions on each a quick view of which PHP version is running on each site.
> Add PHP version to `valet links` output table

- cli/valet.php
This PR adds a confirmation to the tld command to warn about its usage and unexpected results. It also indicates that this isn't an officially supported feature and should be used with caution.
> Confirm tld command

- cli/Valet/PhpFpm.php
- tests/PhpFpmTest.php
Resolves https://github.com/laravel/valet/issues/1241
`Site::getSites()` is now adding "PHP Version" output. Introduced in https://github.com/laravel/valet/pull/1229. On that process Site:getPhpVersion() is passing `null` to `PhpFpm::normalizePhpVersion()` that is breaking  commands like `valet which-php` This PR should fix that.
> Remove preg_replace deprecation warning

- cli/Valet/Ngrok.php
Every time I run `valet share` it opens the tunnel successfully, then shows an error message related to fetch-share-url with this error message.  
```
cURL error 7: Failed to connect to 127.0.0.1 port 4041 after 0 ms: 
Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
for http://127.0.0.1:4041/api/tunnels
```
<details>
<summary> 🔽 Video demonstration of the issue </summary>
https://user-images.githubusercontent.com/13833460/193427493-70538245-a7b2-4634-b8e8-5b5967888a5f.mp4
</details>
This error was happening for a while. I ignored this for a few months. A few days back I was collaborating with a co-worker and he thought valet share is broken as this error always popup for him as well. So I thought of finding the underlying issue. 
Tunnel URL checker …
> Valet fetch-share-url issue fix

- cli/drivers/BedrockValetDriver.php
I'd experienced an issue with the bedrock valet driver for awhile specific to the custom wp-admin route provided by plugins, like the hidden backend feature in iThemes security. 
I finally dug into it and found that the driver is out of sync with the WordPress driver and had a few headers missing from the other drivers. So I tested updating it to match the WordPress driver and it fixed my problem. 
This uses the built in routing available instead of assuming that the folder has an index.php or is part of WordPress core. 
If accepted please kindly add [hacktoberfest-accepted] label too, thanks.
> Fix bedrockvaletdriver

- cli/Valet/Site.php
- tests/SiteTest.php
(copied from Issue #1298 for context):
**Description:**
TL;DR: If your site name contains your TLD (e.g. if your TLD is `.test` and your site name contains `.test`) it will be removed inappropriately.
In line with our regular site setup we have the same locally with valet:
- portal.test-work.test
- welcome.test-work.test
The moment it goes wrong is when I try to use the `isolate` option. Then I get an error: `portal-work isn't found as site name`. That is correct as it is indeed `portal.test-work`. The problem seems to be that `.test` is removed not just at the end, but just as it is found in the site name.
Searches on internet doesn't bring any solutions to the table.
**Steps To Reproduce:**
- add a link to your project with a specific site name in line with ours e.g. `portal.test-work` …
> When formatting provided site name, only remove .tld if it's at the end

- cli/stubs/fastcgi_params
- cli/stubs/valet.conf
When using the Laravel DebugBar with the `capture_ajax` flag set to `true`, developers may encounter 502 Bad Gateway errors. This is due to DebugBar's AJAX request monitoring exceeding the FastCGI buffer limit.
This PR increases the size of the buffer. While it is not guaranteed to fix the problem, the increased buffer size should solve the issue for most developers. Further discussion on this subject can be [found in this issue on the DebugBar repo](https://github.com/barryvdh/laravel-debugbar/issues/251).
> Prevent 502 errors when using AJAX

- cli/Valet/Drivers/BasicWithPublicValetDriver.php
- cli/Valet/Drivers/ValetDriver.php
- tests/Drivers/BaseDriverTestCase.php
- tests/Drivers/BasicValetDriverTest.php
- tests/Drivers/BasicWithPublicValetDriverTest.php
- tests/Drivers/BedrockValetDriverTest.php
- tests/Drivers/CraftValetDriverTest.php
- tests/Drivers/DrupalValetDriverTest.php
- tests/Drivers/JoomlaValetDriverTest.php
- tests/Drivers/KirbyValetDriverTest.php
- tests/Drivers/ValetDriverTest.php
- tests/Drivers/WordPressValetDriverTest.php
Closes #1309.
Replaces #1303.
Requires a bump to v4 because it's backwards compatibility breaking if someone was relying on the old behavior (which can be seen described in #1309).
I split off `BasicValetDriver` and `BasicWithPublicValetDriver` so sites with `public` are better corralled in terms of what files they serve, and so that both drivers can be much simpler.
> Re-work how BasicValetDriver serves files in projects with and without `public/` directory

- cli/Valet/Ngrok.php
- cli/app.php
- tests/NgrokTest.php
This allows users to set their ngrok auth token, now required for all usages of `valet share`.
> Add `set-ngrok-token` command

- cli/Valet/Brew.php
- cli/Valet/Drivers/BasicValetDriver.php
- cli/Valet/Drivers/BasicWithPublicValetDriver.php
- cli/Valet/Drivers/LaravelValetDriver.php
- cli/Valet/Drivers/Specific/BedrockValetDriver.php
- cli/Valet/Drivers/Specific/CakeValetDriver.php
- cli/Valet/Drivers/Specific/Concrete5ValetDriver.php
- cli/Valet/Drivers/Specific/ContaoValetDriver.php
- cli/Valet/Drivers/Specific/CraftValetDriver.php
- cli/Valet/Drivers/Specific/DrupalValetDriver.php
- cli/Valet/Drivers/Specific/KirbyValetDriver.php
- cli/Valet/Drivers/Specific/Magento2ValetDriver.php
- cli/Valet/Drivers/Specific/NeosValetDriver.php
- cli/Valet/Drivers/Specific/StatamicV1ValetDriver.php
- cli/Valet/Drivers/Specific/StatamicValetDriver.php
- cli/Valet/Drivers/Specific/SymfonyValetDriver.php
- cli/Valet/Drivers/Specific/Typo3ValetDriver.php
- cli/Valet/Drivers/ValetDriver.php
- cli/Valet/Server.php
- cli/stubs/SampleValetDriver.php
Drop a few usages of PHP 8+ features so that users can isolate individual sites to PHP 7.4.
This still requires running PHP 8+ at the system level, but at least allows users to isolate certain sites to PHP 7.4.
> Support isolated sites running PHP 7.4

- cli/Valet/Configuration.php
- cli/Valet/Status.php
- cli/Valet/Upgrader.php
- cli/app.php
- cli/includes/facades.php
- tests/BaseApplicationTestCase.php
- tests/CliTest.php
- tests/SiteTest.php
- tests/StatusTest.php
Add a `status` command that checks to make sure Valet and its services are installed, running, and configured correctly.
> Add status command

- cli/Valet/Site.php
When creating a certificate, if the result of the command starts with "Permission denied" it doesn't know that the permission was denied, so it doesn't try to run as root.
The current check will only work if the result contains "Permission denied" but will fail if the result _starts with_ "Permission denied" since that will return `0`.
I also wasn't sure which branch to PR this into, but it looks like `master` is typically where things get PR'd into. Let me know if it needs to be into a different branch and I can change it.
> Fixes permission denied check when result starts with 'Permission denied'

- cli/Valet/Composer.php
- cli/Valet/Expose.php
- cli/app.php
- cli/includes/helpers.php
- tests/ComposerTest.php
Depends on https://github.com/beyondcode/expose/pull/363, which hasn't been merged or released yet.
I want to update this to check for the version number of Expose as a dependency once this feature is tagged/released.
> Implement `valet fetch-share-url` when working with Expose

- cli/Valet/Drivers/BasicValetDriver.php
- cli/Valet/Drivers/BedrockValetDriver.php
- cli/Valet/Drivers/WordPressValetDriver.php
`BasicValetDriver` and a few drivers which extend it set the `SERVER_ADDR` to `127.0.0.1`. To be honest, I'm not sure what circumstance actually requires this.
Here's the PR that introduced it, which doesn't tell us much: https://github.com/laravel/valet/pull/380
So, in order to support local network sharing in #1284, I'm going to make what I hope a very narrow change that sets it to `127.0.0.1` only if it's `null`.  It doesn't break any tests and doesn't break my environment, so hopefully I'm understanding correctly that this is workable.
I originally wrote this using `??=` but we're stuck on PHP 7.2+.
> Make 127.0.0.1 SERVER_ADDR definition only if null

- server.php
This PR enables a rudimentary version of local network sharing with the fix mentioned in (https://github.com/laravel/valet/issues/440#issuecomment-579830736). This pull request was suggested in (https://github.com/laravel/docs/pull/8267) by @driesvints.
I've tested the fix locally and it does enable local network sharing, though it's rudimentary at best since assets don't load properly given the URL doesn't match.
For example, if I have `http://laravel.test` and access is via local network sharing `http://192.168.1.111/laravel.test`, the site does load. But the asset URLs will use `http://laravel.test` and thus not load. I'm not sure if that is due to the `@vite` directive or something else. The same thing happens with the `asset` helper, which might be because of the `APP_URL`.
I did …
> Enable local network sharing

- cli/app.php
This PR  improves the `valet link` command by adding an `--isolate` option to allow users to link, secure and isolate a site in one command.
**Before**
```bash
valet link --secure && valet isolate
```
**After**
```bash
valet link --secure --isolate
```
Please note that the `--isolate` option requires a `.valetphprc` file in the projects root directory as I could not get `$this->runCommand`  to accept any additional arguments / options.
> Add php isolation from link command

- .gitattributes
- .github/workflows/coding-standards.yml
- .styleci.yml
- README.md
- cli/Valet/Brew.php
- cli/Valet/Diagnose.php
- cli/Valet/DnsMasq.php
- cli/Valet/Nginx.php
- cli/Valet/Ngrok.php
- cli/Valet/PhpFpm.php
- cli/Valet/Site.php
- cli/Valet/Valet.php
- tests/SiteTest.php
This PR sets up Pint to lint code and fail when code isn't styled according to Laravel's coding standards. It will only auto-commit when it's run on master.
This PR also includes the first run and fixes by Pint.
> Use Pint for Code Styling

- cli/app.php
- valet
Closes #1367.
E.g., to run this command:
```bash
valet php -v
```
When you've linked a site using a name other than the directory name; for example:
```bash
cd /tmp
mkdir my-site
cd my-site
valet link different-name-than-folder
valet isolate different-name-than-folder php@8.0
```
This PR allows you to run this:
```bash
valet php --site=different-name-than-folder -v
```
> Update php and composer commands to allow passing in specific site

- cli/Valet/Drivers/Specific/BedrockValetDriver.php
Addresses the issue that prompted #1342 by checking for Bedrock-specific Composer dependencies in addition to the existing checks.
> More robust check for Bedrock environments

- cli/Valet/Drivers/LaravelValetDriver.php
Fixes #1384
Since Valet 4 uses Ngrok v3, this change is needed to accommodate the change ngrok made:
> In ngrok v3 the `X-Original-Host` header was replaced with the more standard `X-Forwarded-Host` to better align with web standards.
> More Info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host
Credit to @streamingsystems for doing the legwork.
> [v4] Fix ngrok.io proxy/forwarding detection

- cli/Valet/Configuration.php
- tests/CliTest.php
When composer installing valet, the config.json does not exist yet. If we do a status check like valet status, the non existing config file is read. Which throws an error/warning.
```
.. % ./valet status
Checking status...
PHP Warning:  file_get_contents(/Users/someone/.config/valet/config.json): Failed to open stream: No such file or directory in /Users/someone/Development/Tools/valet/cli/Valet/Filesystem.php on line 84
Warning: file_get_contents(/Users/someone/.config/valet/config.json): Failed to open stream: No such file or directory in /Users/someone/Development/Tools/valet/cli/Valet/Filesystem.php on line 84
Valet status: Error
+------------------------------------------+----------+
| Check                                    | Success? | …
```
> Fix read non existing config file

- cli/Valet/Drivers/Specific/RadicleValetDriver.php
This adds a simple driver for [Radicle](https://roots.io/radicle), an opinionated boilerplate for WordPress projects with the [Roots](https://roots.io/) stack.
This PR is a variation of (https://github.com/laravel/valet/pull/1409), which was closed in favor of this driver.
(Re-opened from [#1412](https://github.com/laravel/valet/pull/1412))
> Add driver for Radicle

- cli/Valet/Brew.php
- tests/BrewTest.php
Fixes #1407
Homebrew's support policy now aggressively disables older versions earlier than it did previously. That is why we tap the `shivammathur/php` repository.
But since Homebrew also now "keeps" those old formulae but marks them as disabled, when Valet runs `brew install php@7.4` it fails because Homebrew just aborts due to its flags in the outdated formula. (They mark it as "disabled" and/or "keg_only :versioned_formula".) To override that we must use `brew install shivammathur/php/php@7.4` internally.
Therefore, we need to maintain a list of which PHP Versions we wish to specifically prefix with the `shivammathur/php` tap in order to bypass Homebrew's flags.
**ANNUAL MAINTENANCE**
1. This PR adds the array of `LIMITED_PHP_VERSIONS` which we will have to update annually when new …
> Install older PHP versions via alternate tap

- valet
If the PHP executable path has a space in it, it breaks valet. For example, when using the new Laravel Herd which stores its config and binaries under `~/Library/Application Support/Herd/...`.
May help with https://github.com/laravel/valet/issues/1395
> Add quotes around $PHP

- cli/Valet/DnsMasq.php
This PR ensures that the DNSMasq resolver configuration file only gets deleted when Laravel Herd is not installed.
Right now this introduces a bug when a user:
1. Installs Herd
2. Uninstalls Valet
As Valet then deletes the DNSMasq resolver that Herd still uses.
> Only delete DNSMasq resolver when Herd is not installed

- cli/Valet/DnsMasq.php
- cli/Valet/PhpFpm.php
- cli/app.php
- tests/CliTest.php
Fixes #1419
Adds:
- `valet stop dnsmasq`
- `valet stop all` (which includes php, nginx, dnsmasq) ... while `valet stop` still only stops nginx/php as it always has.
- When `valet stop` is called without a service name, a message indicates that dnsmasq can also be stopped via `valet stop dnsmasq`
- Aside: _phpfpm_ now also displays a message when stopping; previously it was silent.
> Add "valet stop dnsmasq" option

- cli/app.php
In the original PR (https://github.com/laravel/valet/pull/757), we included Mailhog and Redis, but it's always bothered me because they're not actually installed by default.
This PR removes them and only has default log items that are actually installed.
> Drop Mailhog and Redis from default logs list, since Valet doesn't install them

- cli/Valet/Drivers/LaravelValetDriver.php
When PHP files other than index.php exist in /public/ this allows them to be served by the Laravel driver.
I discussed this previously at: https://github.com/laravel/valet/discussions/1430#discussioncomment-6536474 ... but I think it's safe to include in the core LaravelValetDriver by default.
> Allow LaravelValetDriver to serve other /public/*.php files

- cli/app.php
- composer.json
- tests/CliTest.php
Related to #1386.
Tested in laravel/valet v4.1.2 with [mnapoli/silly](https://github.com/mnapoli/silly) v1.8.2 and [symfony/console](https://github.com/symfony/console) v6.2.5.
~~🟡 Unfortunately, a bug introduced in mnapoli/silly v1.8.1 breaks all arguments in `runCommand()` method preventing this pull request from resolving the isolation issue. See mnapoli/silly#69 for details and mnapoli/silly#70 for pull request.~~
🟢 Bug resolved in [mnapoli/silly v1.8.3](https://github.com/mnapoli/silly/releases/tag/1.8.3).
Passing a custom hostname to the `link` command with the `--isolate` argument will result in either a mismatched site being isolated or the site not being found:
```sh
~/Projects/example.com/www/_codebase
$ valet link example --secure --isolate
A [example] symbolic link has been …
```
> Fix link command's `--isolate` argument with custom name

- cli/Valet/Drivers/Specific/Magento2ValetDriver.php
Fix magento2 driver + simplify, let mode determine by Magento env config
Fixes https://github.com/laravel/valet/discussions/1119 and https://github.com/laravel/valet/issues/592
> Fix magento2 driver

- cli/Valet/Site.php
- tests/CliTest.php
- tests/SiteTest.php
This PR adds support for proxying multiple domains at once with a comma separated list of domains, such as `valet proxy my-domain,sub.my-domain http://127.0.0.1:8000`
The change is backwards compatible, since I explode the URL by comma, if there's no comma present it works as before.
Reason for this change is working locally with Octane can be a bit frustrating. We have an app that uses multiple domains and we use Valet to proxy those domains to Octane. However, currently we'd have to run these commands:
```sh
valet proxy domain http://127.0.0.1:8000
valet proxy sub.domain http://127.0.0.1:8000
valet proxy api.domain http://127.0.0.1:8000
```
This not only takes a long time, Valet also restarts nginx after each command, prompting for the sudo password every time.
With this change it can …
> Add support for proxying multiple domains at once

- cli/stubs/etc-phpfpm-valet.conf
Many have reported that these changes "do" help the problem. 
And yet many others have reported that they make no difference.
Your mileage may vary. But, contributing this PR for the benefit of those for whom it "does" help.
To activate: simply run `valet install` after `composer global upgrade laravel/valet -W` to get the version of Valet this is merged into.
Closes #1433
This PR is merely a bandage for a broader problem that exists in the PHP build for MacOS. See the issue referenced above for discussion and links to Homebrew and PHP repository discussions. The problem is not in Homebrew, but in the PHP build published by the PHP core. Chime in on the PHP discussion if you want to stir up more active participation for a proper fix, telling them that you're a Mac user encountering the …
> Bandage for 502 errors using Gettext/PostgreSQL/MongoDB

- cli/Valet/Site.php
- cli/stubs/secure.proxy.valet-legacy.conf
- cli/stubs/secure.proxy.valet.conf
- cli/stubs/secure.valet-legacy.conf
- cli/stubs/secure.valet.conf
Updated the config so it will work for fresh installs.
removed http2 and http2_push_preload because they are deprecated in latest Nginx versions.
> handle deprecated http2_push_preload conf for nginx >= 1.25.1

- cli/Valet/Ngrok.php
- tests/NgrokTest.php
Every time I'm using `valet fetch-share-url` it's giving this error
`There is no Ngrok tunnel established for ***********.test`
During deep diving, I found that my tunnel is using HTTPS protocol which is why it's unable to get the shared URL!
This pull request will solve this issue!
> Update "fetch-share-url" to pull correct URL for HTTPS tunnels, not just HTTP

- cli/Valet/Site.php
- cli/app.php
- tests/CliTest.php
I was helping a teammate today resolve an issue with a certificate issue locally. After discovering the cert had expired, I thought it might be nice to expose certificate expiration dates when listing secured sites. It would also be nice to be able to renew those certs.
This PR adds both of those features.
> added the ability to renew certs and view their expiration dates

- cli/Valet/Site.php
A reasonable default is set here, consistent with the default set in other places.
Fixes #1464
Updates #1461
@driesvints Can you review and consider releasing a patch, since this is a breaking bug that occurs on `valet install` (which people run not only to install Valet, but also after upgrading it)
> Allow renew() to be called without parameters

- composer.json
Fixes #1480
Updated composer.json to include support for Illuminate v11 and Symfony v7
> Support Illuminate:11 and Symfony:7

- cli/Valet/Server.php
- tests/ServerTest.php
While removing a directory that is parked in Valet. I encountered an error originating from Herd's Valet, though the issue lies with Valet itself. And from a user's perspective, I believe Valet should remain operational even if one of the paths is invalid
Introducing a command such as `valet check` would be beneficial. It could report on Valet's status, confirming if all paths are correct or if any path is invalid.
> Ignore invalid paths

- cli/Valet/Site.php
As a follow-up to #1461, this PR changes the certificate trust logic only to need to trust the `LaravelValetCASelfSigned.pem` certificate. Since all site certificates are generated from this CA, trusting the CA makes trusting the site certificate redundant. 
I noticed my `LaravelValetCASelfSigned.pem` was not trusted on my system, so I added a check for that anytime `secure` is called to ensure the root CA is trusted. 
This will make sure the sudo call to add an entry to the system keychain is called at most once when calling the renew command. Once the CA is trusted, there will be no need to authenticate when calling `secure` or `renew` commands.
I left the `unsecure` command alone since it won't hurt to clean up old certificates if needed.
> Trust CA Certificate only

- cli/app.php
- tests/CliTest.php
This PR adds the ability to specify aPHP version to restart. This reduces the time it takes to restart PHP on system with multiple PHP versions installed when change an ini value or troubleshooting.
Let me know if this is of interest to the project and if I should add similar functionality for starting and stopping php.
> Allow specifying php version to restart

- server.php
Similar issue as in https://github.com/laravel/prompts/pull/146. To make packages like `symfony/var-dumper` available globally you prepend the global Composer autoload.php like so:
```
// php.ini
auto_prepend_file = ${HOME}/.composer/vendor/autoload.php
```
From: https://symfony.com/doc/current/components/var_dumper.html
In Valet this can result in
```
( ! ) Warning: Constant VALET_HOME_PATH already defined in ~/.composer/vendor/laravel/valet/server.php on line 12
Call Stack
#	Time	Memory	Function	Location
1	0.0354	571296	{main}( )	.../server.php:0
2	0.0380	571488	define( $constant_name = 'VALET_HOME_PATH', $value = '~/.config/valet' )	.../server.php:12
( ! ) Warning: Constant VALET_STATIC_PREFIX already defined in ~/.composer/vendor/laravel/valet/server.php on line 13
Call Stack
#	Time …
```
> fix: Warning: Constant VALET_* already defined in X

- cli/Valet/Configuration.php
This fixes an issue where running commands like `valet link foo` would cause the `paths` config array in ~/.config/valet/config.json to turn into an object with non-sequential keys. This in turn caused phpmon to fail with "Laravel Valet configuration file invalid or missing", when it tried to parse the config file.
> Add values() call to reset keys after modifying paths

- cli/Valet/Site.php
When trying to reproduce https://github.com/laravel/valet/issues/1487, I was able to get a Site in this state by following these steps:
1. Fresh install of brew and Valet on macOS 14.5 (via [VirtualBuddy](https://github.com/insidegui/VirtualBuddy))
2. Install valet v4.6.0
3. secure a site
4. Manually remove the CA from Keychain Access.app
5. Site should still be valid, since its own cert is trusted.
6. Upgrade Valet to v4.7.0
7. Run `valet install`
8. This calls renew, which also calls secure on every site. Since the CA is not trusted, the user will be prompted for their password to trust the CA in the System Keychain. Instead of approving, **Click "Cancel"**
9. This will yield the NET::ERR_CERT_AUTHORITY_INVALID error, since the old site cert was removed from the System Keychain.
This PR …
> Require Trusting CA when securing sites

- cli/Valet/Cloudflared.php
- cli/app.php
- cli/includes/facades.php
- valet
This adds a new way of sharing websites using `cloudflared`, specifically something called ["quick tunnels"](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/do-more-with-tunnels/trycloudflare/). These don't require registration and are free of charge to use. It's also possible to use your own domain for sharing by authenticating and configuring a custom tunnel. However, the basic usage requires zero setup.
> Add a new share tool, cloudflared

- .github/workflows/tests.yml
- README.md
- cli/Valet/Brew.php
Include PHP 8.4 in the list of supported PHP versions in both Valet Brew and GitHub Actions test matrix. This ensures compatibility and testing for the latest PHP release.
---
This fixes the `Unable to determine linked PHP when parsing '8.4'` issue when using Valet using PHP version 8.4
> Add support for PHP 8.4

- valet
There was a typo in my previous PR that led to a problem passing extra arguments to share tools. Fixes #1494
> Fix extra parameters for share tool, fixes #1494

- cli/Valet/Site.php
- cli/app.php
This PR adds the ability to renew the Certificate Authority certificate optionally when running the `valet renew --ca` command. Additionally, it adds the ability to view the CA certificate's expiration date through `valet secured --ca`.
This should resolve the issue highlighted in #1496. It may also resolve https://github.com/laravel/valet/issues/1487, but I don't think I was able to verify if the CA expired. 
My comment [here](https://github.com/laravel/valet/issues/1496#issuecomment-2477759775) summarizes the scenario pretty well how users may experience this issue, but I would wager to guess it should be an increasingly uncommon scenario, given new CAs should have 20 years of validity.
> Add the ability to renew the Certificate Authority certificate

- cli/Valet/Site.php
This PR fixes bad replacement regex for loopbacks mentioned in #1503.
Fixes #1503.
> Fixes bad regex for loopback replacement for Issue #1503

- .github/workflows/tests.yml
- composer.json
- tests/BrewTest.php
Added `DataProvider` attribute, to support newer PHPUnit, in order to support latest `yoast/phpunit-polyfills`.
Closes #1512 which only did part of the update
> Add PHPUnit 12 support, and upgrade phpunit-polyfills

- cli/Valet/Brew.php
- cli/Valet/PhpFpm.php
- tests/PhpFpmTest.php
While my PR #1514 fixed recreating the FPM configs, it introduced a different issue:
Due to the use of `utilizedPhpVersions()`, the code now also configured the FPM config for the alias `php` version. 
So e.g. on my system it returned these versions:
- php
- php@8.4
- php@8.3
- php@8.2
This caused it to invoke the configure function 4 times, once for each version.
For `php` it was invoked with an empty version string argument and thus caused overwriting the FPM config for (in my case) php@8.4, templated with `valet.sock`, instead of the correct `valet84.sock`.
The nginx sites that were configured to proxy their requests to the `valet84.sock` then failed because it did not exist anymore.
We fixed this by always including the actual linked PHP version via the `linkedPhp` function. This …
> fix(php-fpm): correct socket creation

- cli/Valet/Drivers/Specific/CraftValetDriver.php
When applying https://github.com/craftcms/security-patches to a Craft project, the fix for [CVE-2024-56145](https://github.com/advisories/GHSA-2p6p-9rc9-62j9) breaks sites served by Valet (and Herd). 
This fix allows these sites to work when using Valet (and Herd).
> Update CraftValetDriver for compatbility with craftcms/security-patches

- cli/Valet/PhpFpm.php
Change how the php-memory-limits.ini is managed because when changed between PHP versions, all the configuration added previously is overriden and it is a waste of time if you work with several PHP versions during the day
> Create php-memory-limits.ini only one time

- cli/Valet/Drivers/Specific/ContaoValetDriver.php
- tests/Drivers/ContaoValetDriverTest.php
This PR updates the `ContaoValetDriver` to support current Contao versions (from Contao 4.9).
`/web/app.php` was used until to Contao 4.8, which was released in August 2019, later versions use `index.php` instead of `app.php`.
I don't think it makes sense to still support older versions than 4.8, because they all are unsupported since 2019. But if you still want to support them, I can add it again.
Current versions also use the `public` directory, but `web` is still supported and is probably still in use by a few people.
I have also added support for the [Contao Manager](https://github.com/contao/contao-manager), which usually resides in `/public/contao-manager.phar.php` and the preview mode, which uses the `preview.php` file.
> Update `ContaoValetDriver` to support current Contao versions

- cli/Valet/Site.php
- cli/stubs/openssl.conf
As mentioned in #1530, I recently ran into some issues with Valet certs not passing OpenSSL's X509 strict mode, which was enabled by default in Python 3.13. This made it difficult for python apps to communicate with php apps run under Valet during development.
This PR adds the necessary X509 extensions to both the CA and per-site leaf certificates to satisfy strict mode.
Note that the reference to the extension config file has been removed from the CSR creation command as the AKID extension can't be added without the CA certificate present (which it isn't when running this command). This has no effect on the final certificate as the CSR extensions were being overwritten when the certificate was signed anyway.
I have tested the migration pathway of this change under VirtualBuddy, and …
> fix(TLS): create OpenSSL strict-mode compliant certs
